### ISSUE TITLE
heap-buffer-overflow in TRandom3

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#10016]
After #10005 is merged, the test `tutorial-roofit-rf408_RDataFrameToRooFit-py` will fail due to a `heap-buffer-overflow`:
```
1177: READ of size 4 at 0x61e0000d0690 thread T15
1177:     #0 0x7f83a02588ec in TRandom3::Rndm() /home/jhahnfel/ROOT/src/math/mathcore/src/TRandom3.cxx:129:8
1177:     #1 0x7f83a024c8db in TRandom::Gaus(double, double) /home/jhahnfel/ROOT/src/math/mathcore/src/TRandom.cxx:306:11
```

Note: There may be other problems in the test after this issue is fixed. Please check locally with an instrumented build that the test passes afterwards!

**Comment by hahnjo** [comment]
Seems to pass now, closing
