### ISSUE TITLE
heap-buffer-overflow in RNtuple

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#10011]
After #10005 is merged, a couple of tests will fail due to a `heap-buffer-overflow`:
 * `gtest-tree-ntuple-v7-test-ntuple-basics`
 * `gtest-tree-ntuple-v7-test-ntuple-rdf`
 * `gtest-tree-ntuple-v7-test-ntuple-view`
 * `gtest-tree-ntuple-v7-test-ntuple-show`

Stack trace (for the first test) is:
```
393: WRITE of size 4 at 0x6020000d2a50 thread T0                                                                                                                                                                                              
393:     #0 0x7efdd569f028 in ROOT::Experimental::RClusterSize::RClusterSize() /home/jhahnfel/ROOT/src/tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx:61:21
393:     #1 0x7efdd4d41a7f in ROOT::Experimental::Detail::RFieldValue::RFieldValue<ROOT::Experimental::RClusterSize>(ROOT::Experimental::Detail::RColumnElementBase const&, ROOT::Experimental::Detail::RFieldBase*, ROOT::Experimental::RClusterSize*) /home/jhahnfel/ROOT/src/tree/ntuple/v7/inc/ROOT/RFieldValue.hxx:75:19
393:     #2 0x7efdd4d259d1 in ROOT::Experimental::RCollectionField::GenerateValue(void*) /home/jhahnfel/ROOT/src/tree/ntuple/v7/inc/ROOT/RField.hxx:519:14
393:     #3 0x7efdd4cec7d8 in ROOT::Experimental::Detail::RFieldBase::GenerateValue() /home/jhahnfel/ROOT/src/tree/ntuple/v7/src/RField.cxx:268:11
393:     #4 0x7efdd4e101b2 in ROOT::Experimental::RNTupleModel::Clone() const /home/jhahnfel/ROOT/src/tree/ntuple/v7/src/RNTupleModel.cxx:74:49

[...]

393: 0x6020000d2a51 is located 0 bytes to the right of 1-byte region [0x6020000d2a50,0x6020000d2a51)
393: allocated by thread T0 here:
393:     #0 0x557ff8 in malloc (/home/jhahnfel/ROOT/build-clang-asan-debug/tree/ntuple/v7/test/ntuple_basics+0x557ff8)
393:     #1 0x7efdd4cec70b in ROOT::Experimental::Detail::RFieldBase::GenerateValue() /home/jhahnfel/ROOT/src/tree/ntuple/v7/src/RField.cxx:266:18
393:     #2 0x7efdd4e101b2 in ROOT::Experimental::RNTupleModel::Clone() const /home/jhahnfel/ROOT/src/tree/ntuple/v7/src/RNTupleModel.cxx:74:49
```

Note: There may be other problems in the tests after this issue is fixed. Please check locally with an instrumented build that the tests pass afterwards!

**Comment by jalopezg-r00t** [comment]
Thanks for reporting this, @hahnjo!  I will take a look at it soon  :-)
