### ISSUE TITLE
Thread-safety issue in TClassEdit (StdLen)?  [6.24.06]

### ISSUE THREAD

**Issue by scott-snyder** [root-project/root#10353]
hi -

This is relevant to root 6.24.06, but the issue described appears to be present in 6.26.00 as well.

I recently saw a report of a crash in the ATLAS trigger code
(https://its.cern.ch/jira/browse/ATR-25254) that included this stack trace:

```
#5  <signal handler called>
#6  0x0000000000000000 in ?? ()
#7  0x00007f68343efc71 in TClassEdit::GetSplit(char const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, int&, TClassEdit::EModType) () from /sw/atlas/sw/lcg/releases/LCG_101_ATLAS_14/ROOT/6.24.06/x86_64-centos7-gcc11-opt/lib/libCore.so
#8  0x00007f68343f12f1 in TClassEdit::TSplitType::TSplitType(char const*, TClassEdit::EModType) () from /sw/atlas/sw/lcg/releases/LCG_101_ATLAS_14/ROOT/6.24.06/x86_64-centos7-gcc11-opt/lib/libCore.so
#9  0x00007f68343f23f1 in TClassEdit::GetNormalizedName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::basic_string_view<char, std::char_traits<char> >) () from /sw/atlas/sw/lcg/releases/LCG_101_ATLAS_14/ROOT/6.24.06/x86_64-centos7-gcc11-opt/lib/libCore.so
#10 0x00007f683440dc8b in TClass::GetClass(char const*, bool, bool, unsigned long, unsigned long) () from /sw/atlas/sw/lcg/releases/LCG_101_ATLAS_14/ROOT/6.24.06/x86_64-centos7-gcc11-opt/lib/libCore.so
#11 0x00007f683441e338 in TClassRef::InternalGetClass() const () from /sw/atlas/sw/lcg/releases/LCG_101_ATLAS_14/ROOT/6.24.06/x86_64-centos7-gcc11-opt/lib/libCore.so
#12 0x00007f682e411d18 in TScopeAdapter::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool) () from /sw/atlas/Athena/22.0.60/InstallArea/x86_64-centos7-gcc11-opt/lib/libDataModelRoot.so
```

The place in the code where it's crashing in GetSplit after it calls
to StdLen:

```
   if ( mode & kDropStd) {
      unsigned int offset = (0==strncmp("const ",full.c_str(),6)) ? 6 : 0;
      RemoveStd( full, offset );
   }
```

where RemoveStd is inlined:

```
static void RemoveStd(std::string &name, size_t pos = 0)
{
   size_t len = StdLen({name.data()+pos,name.length()-pos});
   if (len) {
```

So, it calls to StdLen, which apparently then crashes by branching to 0.
It's unfortunately difficult to then tell exactly why that happened.
FWIW, the registers at the crash were:

```
  rip: 0033:0000000000000000           eflags: 0000000000010202
  rax: 00000000ffffffeb   rbx: 0000000000000220
  rcx: 0000000000000078   rdx: 0000000000000000
  r08: ffffffffffffffff   r09: 00007f68354af4d0
  r10: 72543a3a444f4178   r11: 0000000000000006
  r12: 00000000961170c0   r13: 00007f67e4395a90
  r14: 0000000000000000   r15: 00007f683459fb22
  rsi: 00000000961170c0   rdi: 000000000000001f
  rbp: 00007f67e4395c28   rsp: 00007f67e4395a48
```

However, the reason i'm writing this up here is that StdLen contains
a mutable, static std::set instance:

```
               static ShuttingDownSignaler<std::set<std::string>> gInlined;
```

So this appears to be a thread-safety issue, regardless of whether
this is actually reponsible for the observed crash.

There is no lock protecting this in either StdLen or in the TClass
methods that call it.  There is a lock (gCoreMutex) taken in TClass::GetClass,
so we should be safe against other code that's using GetClass.
However, ATLAS code also directly uses TClassEdit in a number of places,
so i think we do have a potential race.

(Though we don't use it from so many places, so it may be feasible
to wrap our uses of TClassEdit with taking gCoreMutex.)

**Comment by pcanal** [comment]
> so i think we do have a potential race.

That's seems very plausible indeed. (There is even a comment pointing out that this code is assuming a lock is already taken).  It should be sufficient to add a spin lock around the 2 accesses.
