### ISSUE TITLE
Reading XYZVectors with TTreeReader is broken in some cases

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#10423]
Reproducer:

```cpp
#include <Math/Vector3D.h>
#include <ROOT/RDataFrame.hxx>
#include <vector>
#include <TClass.h>

int main() {
  {
    TFile f("f.root", "recreate");
    TTree t("t", "t");
    ROOT::Math::XYZVector x(1, 2, 3);
    std::vector<ROOT::Math::XYZVector> y{ROOT::Math::XYZVector(4,5,6)};
    t.Branch("x", &x);
    // original line:
    //     t.Branch("y", &y); // commenting this line "fixes" the problem!
    // Actual trigger:
    auto c = TClass::GetClass("std::vector<ROOT::Math::XYZVector>");  // commenting this line "fixes" the problem!
    t.Fill();
    t.Write();
  }

  TFile f("f.root");
  TTreeReader r("t", &f);
  TTreeReaderValue<ROOT::Math::XYZVector> rx(r, "x");
  r.Next();
  *rx;
}
```
yields:

```
Error in <TTreeReaderValueBase::CreateProxy()>: The branch x contains data of type ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<Double32_t>,ROOT::Math::DefaultCoordinateSystemTag>. It cannot be accessed by a TTreeReaderValue<ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag>>
Error in <TTreeReaderValue::Get()>: Value reader not properly initialized, did you call TTreeReader::Set(Next)Entry() or TTreeReader::Next()?
```

Interestingly, if branch `"y"` is not written out, then branch `"x"` can be read correctly.

**Comment by dudarboh** [comment]
@pcanal, @eguiraud, @Axel-Naumann,

Dear all, could I ask if there is any progress on this?
Looking at the code, I found that somewhat similar problem has already existed:
https://sft.its.cern.ch/jira/browse/ROOT-8731

Wouldn't the solution be straightforward? Maybe I can try to contribute?

cheers

**Comment by Axel-Naumann** [comment]
@pcanal do we really need to teach TTreeReader to check for schema evolution between source and target, or is there maybe a better question that TTreeReader can ask, better than "is source and target class the same?"

**Comment by ferdymercury** [comment]
In master: when running in the interpreter, I do not get any assertion printed, when running with g++, I get:

```
9  0x00007fd17e5998d4 in TTreeReader::SetProxies (this=0x7ffc87ceccc0) at /opt/root_src/tree/treeplayer/src/TTreeReader.cxx:396
#10 0x00007fd17e5994a2 in TTreeReader::Notify (this=0x7ffc87ceccc0) at /opt/root_src/tree/treeplayer/src/TTreeReader.cxx:330
#11 0x00007fd17e5a27c8 in TNotifyLink<TTreeReader>::Notify (this=0x7ffc87cecce8) at /opt/root_src/core/base/inc/TNotifyLink.h:139
#12 0x00007fd17ef7f012 in TTree::LoadTree (this=0x555c5e01ebe0, entry=0) at /opt/root_src/tree/tree/src/TTree.cxx:6497
#13 0x00007fd17e59abbd in TTreeReader::SetEntryBase (this=0x7ffc87ceccc0, entry=0, local=false) at /opt/root_src/tree/treeplayer/src/TTreeReader.cxx:665
#14 0x0000555c34204b1c in TTreeReader::SetEntry(long long) ()
#15 0x0000555c34204ae9 in TTreeReader::Next() ()
#16 0x0000555c3420481e in main ()
```
