### ISSUE TITLE
df105_WBosonAnalysis.py does not convert in notebook using `nbconvert`

### ISSUE THREAD

**Issue by couet** [root-project/root#10430]
### Describe the bug

When building the reference guide the tutorial `df105_WBosonAnalysis.py` does not convert in notebook using `nbconvert`
we get the following errors:

```
$ /usr/bin/python converttonotebook.py /home/sftnight/couet/root/tutorials/dataframe/df105_WBosonAnalysis.py /home/sftnight/rootdoc/notebooks/
0.0331268310547
[NbConvertApp] Converting notebook /home/sftnight/rootdoc/notebooks/df105_WBosonAnalysis.py.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python2
[NbConvertApp] ERROR | Error while converting '/home/sftnight/rootdoc/notebooks/df105_WBosonAnalysis.py.ipynb'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
parser = argparse.ArgumentParser()
parser.add_argument("--lumi-scale", type=float, default=0.001,
                    help="Run only on a fraction of the total available 10 fb^-1 (only usable together with --full-dataset)")
parser.add_argument("--full-dataset", action="store_true", default=False,
                    help="Use the full dataset (use --lumi-scale to run only on a fraction of it)")
parser.add_argument("-b", action="store_true", default=False, help="Use ROOT batch mode")
parser.add_argument("-t", action="store_true", default=False, help="Use implicit multi threading (for the full dataset only possible with --lumi-scale 1.0)")
args = parser.parse_args()

if args.b: ROOT.gROOT.SetBatch(True)
if args.t: ROOT.EnableImplicitMT()

if not args.full_dataset: lumi_scale = 0.001 # The preskimmed dataset contains only 0.01 fb^-1
else: lumi_scale = args.lumi_scale
lumi = 10064.0
print('Run on data corresponding to {:.2f} fb^-1 ...'.format(lumi * lumi_scale / 1000.0))

if args.full_dataset: dataset_path = "root://eospublic.cern.ch//eos/opendata/atlas/OutreachDatasets/2020-01-22"
else: dataset_path = "root://eospublic.cern.ch//eos/root-eos/reduced_atlas_opendata/w"
------------------

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

SystemExit: 2

NOTEBOOK_CONVERSION_WARNING: Nbconvert failed for notebook df105_WBosonAnalysis.py.ipynb with return code 1
[NbConvertApp] Converting notebook /home/sftnight/rootdoc/notebooks/df105_WBosonAnalysis.py.ipynb to notebook
[NbConvertApp] Writing 14399 bytes to /home/sftnight/rootdoc/notebooks/df105_WBosonAnalysis.py.nbconvert.ipynb
4.87410593033
```

### Expected behavior

It should convert 

### To Reproduce

Execute the command above.

### Possible Fix

I looks like the argument parsing cannot be handled properly in the notebook. It is not possible to fix (I tried) this tutorial easily as the `args` variable is used every where. I suggest to not generate the notebook (for the time being)on this example as it polutes the log of the ref guide build. Experts (@etejedor ? @vepadulano ?) eyes are needed.

**Comment by couet** [comment]
same thing with `df106_HiggsToFourLeptons.py`

**Comment by etejedor** [comment]
Could you check what's the conflicting argument? The Python script is trying to parse some args, but it has some defaults for them. In a notebook, it should just take the defaults.

**Comment by ferdymercury** [comment]
Maybe related: https://discuss.dizzycoding.com/passing-command-line-arguments-to-argv-in-jupyter-ipython-notebook/

A quick fix might be to detect if these scripts are run within a notebook and skip the argparse part?

Taken from: https://gist.github.com/gbishop/acf40b86a9bca2d571fa
```
# try to detect that I'm in a notebook
try:
    __IPYTHON__
except NameError:
    inIPython = False
else:
    inIPython = True
```

**Comment by ferdymercury** [comment]
Side note: there are about 50 notebooks failing in total, but I guess not related to , see https://lcgapp-services.cern.ch/root-jenkins/view/ROOT/job/root-makedoc-master/lastBuild/parsed_console/job/root-makedoc-master/2655/parsed_console/log.html

![image](https://user-images.githubusercontent.com/10653970/164553066-0be620a7-ad2a-4340-a9fd-926512d77770.png)

**Comment by couet** [comment]
> A quick fix might be to detect if these scripts are run within a notebook and skip the argparse part?

That's not that easy. I tried to remove the argparse part on this one (df105_WBosonAnalysis.py) but the parameters returned by argparse are used all over the script. So a re-write of the script is needed.

**Comment by etejedor** [comment]
Could you check what's the conflicting argument? The Python script is trying to parse some args, but it has some defaults for them. In a notebook, it should just take the defaults.

**Comment by couet** [comment]
This is not the only problem with this example. I removed completely the `argparse`management. The script execute well with python. but hone trying to do nbconvert I get:
```
$ python3 converttonotebook.py /home/sftnight/couet/root/tutorials/dataframe/df105_WBosonAnalysis.py /home/sftnight/rootdoc/notebooks
0.022516250610351562
[NbConvertApp] Converting notebook /home/sftnight/rootdoc/notebooks/df105_WBosonAnalysis.py.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] ERROR | Error while converting '/home/sftnight/rootdoc/notebooks/df105_WBosonAnalysis.py.ipynb'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
files = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "df105_WBosonAnalysis.json")))
processes = files.keys()
df = {}
xsecs = {}
sumws = {}
samples = []
for p in processes:
    for d in files[p]:
        # Construct the dataframes
        folder = d[0] # Folder name
        sample = d[1] # Sample name
        xsecs[sample] = d[2] # Cross-section
        sumws[sample] = d[3] # Sum of weights
        num_events = d[4] # Number of events
        samples.append(sample)
        df[sample] = ROOT.RDataFrame("mini", "{}/1lep/{}/{}.1lep.root".format(dataset_path, folder, sample))

        # Scale down the datasets if requested
        if lumi_scale < 1.0:
            df[sample] = df[sample].Range(int(num_events * lumi_scale))
------------------

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-8b7fe3b1229a> in <module>
----> 1 files = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "df105_WBosonAnalysis.json")))
      2 processes = files.keys()
      3 df = {}
      4 xsecs = {}
      5 sumws = {}

NameError: name '__file__' is not defined
NameError: name '__file__' is not defined

NOTEBOOK_CONVERSION_WARNING: Nbconvert failed for notebook df105_WBosonAnalysis.py.ipynb with return code 1
[NbConvertApp] Converting notebook /home/sftnight/rootdoc/notebooks/df105_WBosonAnalysis.py.ipynb to notebook
[NbConvertApp] Writing 13100 bytes to /home/sftnight/rootdoc/notebooks/df105_WBosonAnalysis.py.nbconvert.ipynb
4.609873294830322

```
This example is hopeless....

**Comment by eguiraud** [comment]
I wouldn't say hopeless, this last error looks like we just have to not use `__file__` as it's not defined when doing the notebook conversion..

**Comment by etejedor** [comment]
That last error is caused by the code looking for a json file and using `__file__` to get the directory where the python script is stored, because that's where the json file is also stored. And `__file__` does not exist in the notebook

**Comment by couet** [comment]
ok, you are the experts. suggest me a fix.

**Comment by eguiraud** [comment]
Incoming :smile:

**Comment by eguiraud** [comment]
For the `__file__` error you can use this patch:

```diff
diff --git a/tutorials/dataframe/df105_WBosonAnalysis.py b/tutorials/dataframe/df105_WBosonAnalysis.py
index 00d323f472..d32bb75502 100644
--- a/tutorials/dataframe/df105_WBosonAnalysis.py
+++ b/tutorials/dataframe/df105_WBosonAnalysis.py
@@ -47,7 +47,7 @@ else: dataset_path = "root://eospublic.cern.ch//eos/root-eos/reduced_atlas_opend

 # Create a ROOT dataframe for each dataset
 # Note that we load the filenames from the external json file placed in the same folder than this script.
-files = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "df105_WBosonAnalysis.json")))
+files = json.load(open(os.path.join(ROOT.gROOT.GetTutorialsDir(), "dataframe/df105_WBosonAnalysis.json")))
 processes = files.keys()
 df = {}
 xsecs = {}
```

**Comment by etejedor** [comment]
For the `argparse` issue, you can check if `sys.argv[0]` is `'df105_WBosonAnalysis.py'`, this means you are executing it as a script. If that's not the case, you assume you are in a notebook, and you need to call `parse_args` like this `args = parser.parse_args(args=[])` (note the `args` argument).

**Comment by couet** [comment]
This new way of calling `parse_args ` dow not work for both cases ?

**Comment by couet** [comment]
With `args = parser.parse_args(args=[])` the conversion to notebook is working and the direct execution of the script using python3 also. So I guess we have the solution. I will make a PR.

**Comment by couet** [comment]
PR here: https://github.com/root-project/root/pull/10437
