### ISSUE TITLE
JSRoot.core.js from root.cern server stopped working after migration to 7.1.0

### ISSUE THREAD

**Issue by SergueiEK** [root-project/root#10727]
Hello

I have a Web service that has been using JSRoot script that is taken from the ROOT server with the following reference:

`<script src="https://root.cern/js/latest/scripts/JSRoot.core.js"></script>
`

It used to be working fine with ROOT v6 but after the 'latest' soft link had been moved to 7.1.0 the page stopped working giving the following error in JS console:

```
Uncaught (in promise) TypeError: Failed to resolve module specifier '../modules/core.mjs'. The base URL is about:blank because import() is called from a CORS-cross-origin script.
    at JSRoot.core.js:325:21
    at JSRoot.core.js:3:77
    at JSRoot.core.js:5:3
```

I have fixed the Web service by replacing the 'latest' token in the JSRoot reference with '6.3.4' but I think it will stop working again as soon as this version will be removed from the ROOT server. Am I doing something wrong or otherwise could this problem be fixed?

To reproduce the problem one should create an HTML file with the following content in a Web server and load it from a Web browser:

```
<!DOCTYPE html>
<html>
<head>
<script src="https://root.cern/js/latest/scripts/JSRoot.core.js"></script>
</head>
<body>
</body>
</html>

```

Cheers,

**Comment by bellenot** [comment]
Can you try with
```
<script type="text/javascript" src="https://root.cern.ch/js/latest/scripts/JSRoot.core.js" crossorigin="anonymous"></script>
```

**Comment by linev** [comment]
Which web browser you are using?
On which server?

I do not see problem: https://jsroot.gsi.de/files/tmp/bug.html

If you migrating from JSROOT v6 to v7, please read:

https://github.com/root-project/jsroot/blob/master/docs/JSROOT.md#migration-v6---v7

`JSRoot.core.js` kept only for backward compatibility, one should use modules instead

**Comment by bellenot** [comment]
@linev I see the same error with https://jsroot.gsi.de/files/tmp/bug.html:
```
Uncaught (in promise) TypeError: Failed to resolve module specifier '../modules/core.mjs'. The base URL is about:blank because import() is called from a CORS-cross-origin script.
    at JSRoot.core.js:325:21
    at JSRoot.core.js:3:77
    at JSRoot.core.js:5:3
 ```

**Comment by linev** [comment]
Strange.

Here example with `crossorigin="anonymous"`. 

https://jsroot.gsi.de/files/tmp/bug_anonymous.html

**Comment by bellenot** [comment]
It works:
```
Set jsroot source_dir to https://root.cern/js/latest/, 7.1.0 9/06/2022
```

**Comment by SergueiEK** [comment]
Thank you for the suggestion. Adding crossorigin="anonymous" fixed the problem. 
Without this attribute the https://jsroot.gsi.de/files/tmp/bug.html page produced the same problem as I had originally reported.
I'm using Google Chrome 102 on MacOS BigSur 11.6.4

However once I had the new ROOT version working I have immediately faced another problem. The code that I have been using so far to set default draw option to "lego2" in JSROOT.HierarchyPainter, has stopped working.  This code was suggested to me in this forum last year and it did the trick in the following way:

```
  JSROOT.require('hierarchy').then(() => {
    let h = new JSROOT.HierarchyPainter("opmon", tree);
    
    h._display = h.display;
    h.display = function(itemname, opt) {
      if (!opt) opt = "lego2";
      this._display(itemname, opt);
    }
    ...
```

Can I do the same with v7?
Cheers,
Serguei

**Comment by bellenot** [comment]
I'll let @linev reply to this particular question...

**Comment by linev** [comment]
v7 has absolutely new code management - based on ES6 modules.
Here example how `HierarhcyPainter` should be used:

https://github.com/root-project/jsroot/blob/master/demo/file_hierarchy.htm

**Comment by SergueiEK** [comment]
Thank you for the reference. I have updated my JS scripts to use modules and my Web service works fine now with v7.

May I ask one more question about axis labels for histograms. If a histogram is drawn as 2D image then I can adjust the color, size and offset of the axis labels using the context drop-down menu. However if I draw 2D histogram as 3D image using the "lego2" option then the axis labels drop-down menu still appears but makes no effect on the labels visualisation. None of the selected options works, neither color, not size or offset. The point is that sometimes the labels are so small that they are completely unreadable and it would have been nice to be able to increase the font size. It's also quite annoying that the labels are not aligned to the bins center, but instead are aligned to the bins edges. Is this behaviour expected? Attached image shows the issues.

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/29973760/173081896-841849be-48ca-4c01-84f0-ff3d6c04673e.png">

**Comment by linev** [comment]
> None of the selected options works, neither color, not size or offset

Was not implemented up to now. I will check this next week

**Comment by linev** [comment]
I add support of TAxis attributes for lego plots:

https://jsroot.gsi.de/dev/?json=../files/th2ul.json.gz&opt=lego2

Now most of context menu settings of x/y/z axis should also work.
It is in master branch of JSROOT
