### ISSUE TITLE
Installing with CMAKE_INSTALL_PYTHONDIR different from CMAKE_INSTALL_LIBDIR leads to incorrect runpath configuration

### ISSUE THREAD

**Issue by guicale** [root-project/root#11431]
- [x] Checked for duplicates

### Describe the bug
Installing ROOT with a path for `CMAKE_INSTALL_PYTHONDIR` different than the one for `CMAKE_INSTALL_LIBDIR` leads to problems trying to use the Python modules provided by ROOT, such as the example that follows.

```
$ rootbrowse
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/cppyy/__init__.py", line 60, in <module>
    importlib.import_module(libcppyy_mod_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: libcppyy_backend3_10.so.6.26: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rootbrowse", line 10, in <module>
    import cmdLineUtils
  File "/usr/local/lib/python3.10/dist-packages/cmdLineUtils.py", line 82, in <module>
    import ROOT
  File "/usr/local/lib/python3.10/dist-packages/ROOT/__init__.py", line 22, in <module>
    import cppyy
  File "/usr/local/lib/python3.10/dist-packages/cppyy/__init__.py", line 62, in <module>
    raise ImportError(
ImportError: Failed to import libcppyy3_10. Please check that ROOT has been built for Python 3.10
```

A check with `readelf` reveals the runpath of the libraries installed to `CMAKE_INSTALL_PYTHONDIR` is the reason for this problem.

```
$ readelf -a /usr/local/lib/root/libcppyy3_10.so | grep -i runpath
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:$ORIGIN/../lib/root]
```

```
$ readelf -a /usr/local/lib/python3.10/dist-packages/libcppyy3_10.so | grep -i runpath
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:$ORIGIN/../lib/root]
```

As you can see above, the libraries installed to `CMAKE_INSTALL_PYTHONDIR` have the same runpath as the ones installed to `CMAKE_INSTALL_LIBDIR`, which shouldn't be the case if the two are different directories.

### Expected behavior
The libraries installed to `CMAKE_INSTALL_PYTHONDIR` should have the runpath set to the correct relative location of `CMAKE_INSTALL_LIBDIR` (`$ORIGIN/../../../lib/root` in the previous example).

### To Reproduce
1. Configure the build with `CMAKE_INSTALL_PYTHONDIR` different from `CMAKE_INSTALL_LIBDIR` and with rpath enabled.
2. Compile and install as usual.
3. Try to use the python modules installed by ROOT, such as by running `rootbrowse`.

### Setup
- ROOT version 6.26/06
- Ubuntu 22.04 running on WSL2
- ROOT installed from source with the build config command `CUDACXX=/usr/local/cuda-11.7/bin/nvcc cmake -C config.cmake .. -DCMAKE_CUDA_ARCHITECTURES='86' -Dgnuinstall=ON -Dcuda=ON -Dcudnn=ON -Dtmva-gpu=ON -Dsoversion=ON -Dfortran=ON -DPYTHON_EXECUTABLE=/usr/bin/python -Drpath=ON`, where the file `config.cmake` contains
```
set(CMAKE_INSTALL_PYTHONDIR "lib/python3.10/dist-packages" CACHE PATH "python libraries and modules (same as LIBDIR)")
set(CMAKE_INSTALL_SYSCONFDIR "/etc/root" CACHE PATH "read-only single-machine data (etc/root)")
```

### Additional context
A temporary workaround while this issue is not resolved is to manually modify the runpath of the libraries installed to `CMAKE_INSTALL_PYTHONDIR`, e.g. using `chrpath` or [`patchelf`](https://github.com/NixOS/patchelf).

**Comment by guitargeek** [comment]
Thanks for the report! This should be closed by:
  * https://github.com/root-project/root/pull/18997

Feel free to open a new issue if you encounter similar problems in the future.
