### ISSUE TITLE
[cling] 

### ISSUE THREAD

**Issue by jalopezg-r00t** [root-project/root#11494]
- [X] Checked for duplicates

### Describe the bug
A non-void returning function (specifically, returning `std::vector<ROOT::RDF::RResultPtr<TH1D>>`) that throws, causes `cling::Value::~Value()` to try freeing resources that were, in principle, already released as part of exception handling.  See behavior below:
```c++
root [0] .x pointer_not_allocated_error.cc
free(): double free detected in tcache 2
```

In principle, this seems to be dependent on NRVO.  Crash seems to be avoided either by _(i)_ commenting out
```c++
histograms.push_back(h);
```
; or _(ii)_ changing the `return` statement as follows
```diff
-   return histograms;
+   return {h};
```

### To Reproduce
The issue can be reproduced with the following code in ArchLinux x86_64 with ROOT master:
```c++
vector<ROOT::RDF::RResultPtr<TH1D>> pointer_not_allocated_error(){
    // Create a data frame with 100 rows
    ROOT::RDataFrame rdf(100);

    // Define a new column `x` that contains random numbers and create a histogram
    ROOT::RDF::RResultPtr<TH1D> h = rdf.Define("x", [](){ return gRandom->Rndm(); }).Histo1D("x");

    // Add the histogram to a vector
    vector<ROOT::RDF::RResultPtr<TH1D>> histograms;
    histograms.push_back(h);

    // Attempt to throw an error
   throw std::runtime_error("intended error throw for debugging");

   return histograms;
}
```

### Additional context
For additional context see https://root-forum.cern.ch/t/pointer-not-allocated-when-adding-rresultptr-to-vector/51831/2.

Interesting part of the gdb backtrace follows (thanks @eguiraud!):
```
>>> bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff72a1503 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7251958 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff723b53d in __GI_abort () at abort.c:79
#4  0x00007ffff729563e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff73b4432 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007ffff72ab22c in malloc_printerr (str=str@entry=0x7ffff73b6ff8 "free(): double free detected in tcache 2") at malloc.c:5660
#6  0x00007ffff72ad587 in _int_free (av=0x7ffff73f1ba0 <main_arena>, p=0x55555e7134c0, have_lock=have_lock@entry=0) at malloc.c:4469
#7  0x00007ffff72af9f3 in __GI___libc_free (mem=<optimized out>) at malloc.c:3385
#8  0x00007ffff18d07b4 in std::_Vector_base<ROOT::RDF::RResultPtr<TH1D>, std::allocator<ROOT::RDF::RResultPtr<TH1D> > >::~_Vector_base (this=0x55555881f750) at /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/stl_vector.h:366
#9  0x00007ffff23aa435 in cling::Value::~Value() () from /home/blue/ROOT/master/cmake-build-foo/lib/libCling.so
#10 0x00007ffff21a1869 in TCling::ProcessLine (this=0x5555555ee950, line=0x5555563e9c60 ".X  /tmp/./pointer_not_allocated_error.C", error=0x7fffffffb600) at ../core/metacling/src/TCling.cxx:2633
```

**Comment by ferdymercury** [comment]
Same with master (LLVM22)
