### ISSUE TITLE
Broken pythonization of std::vector<const char*>

### ISSUE THREAD

**Issue by swertz** [root-project/root#11581]
- [x] Checked for duplicates: seems to be similar to #10522 but this is unrelated to complex numbers

### Describe the bug

Trying to declare a `std::vector<const char*>` from python fails in ROOT 6.26 (also tested in master) with:
```
In [1]: import ROOT

In [2]: ROOT.gROOT.GetVersion()
Out[2]: '6.26/00'

In [3]: ROOT.gInterpreter.Declare('std::vector<const char*> test = {"hello"};')
Out[3]: True

In [4]: ROOT.test
Error pythonizing class std::vector<const char*>:
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102rc1/x86_64-centos7-gcc11-opt/lib/ROOT/_pythonization/__init__.py", line 233, in _invoke                                                                                                                         
    user_pythonizor(klass, fqn)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102rc1/x86_64-centos7-gcc11-opt/lib/ROOT/_pythonization/_stl_vector.py", line 37, in pythonize_stl_vector                                                                                                          
    if klass.value_type == 'char':
AttributeError: <class cppyy.gbl.std.vector<const char*> at 0x78c6370> has no attribute 'value_type'. Full details:
  type object 'vector<const char*>' has no attribute 'value_type'
  'std::vector<const char*>::value_type' is not a known C++ class
  'value_type' is not a known C++ template
  'value_type' is not a known C++ enum
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-9dea63bfe1b1> in <module>
----> 1 ROOT.test

/cvmfs/sft.cern.ch/lcg/views/LCG_102rc1/x86_64-centos7-gcc11-opt/lib/ROOT/_facade.py in _fallback_getattr(self, name)
    193             if res:
    194                 return res
--> 195         raise AttributeError("Failed to get attribute {} from ROOT".format(name))
    196
    197     def _finalSetup(self):

AttributeError: Failed to get attribute test from ROOT
```

Creating the object directly from python does not work either:
```
In [5]: t = ROOT.std.vector["const char*"](["hello"])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-fac447a0dff2> in <module>
----> 1 t = ROOT.std.vector["const char*"](["hello"])

TypeError: none of the 2 overloaded methods succeeded. Full details:
  void std::vector<const char*>::push_back(const char*&& __x) =>
    TypeError: could not convert argument 1
  void std::vector<const char*>::push_back(const char*const& __x) =>
    TypeError: could not convert argument 1
```

### Expected behavior

In ROOT 6.24, I can get a reference to the object:
```
In [1]: import ROOT

In [2]: ROOT.gInterpreter.Declare('std::vector<const char*> test = {"hello"};')
Out[2]: True

In [3]: ROOT.test
Out[3]: <cppyy.gbl.std.vector<const char*> object at 0x7f2c7fa19020>

In [4]: ROOT.test[0]
Out[4]: <cppyy.LowLevelView at 0x7f2c6f18e490>

In [5]: ROOT.gROOT.GetVersion()
Out[5]: '6.24/06'
```

### Setup

Tested on ROOT 6.24/06 (LCG101), 6.26/00 (LCG102rc1), master (LCGdev3): the pythonization issue does not appear in 6.24.

**Comment by etejedor** [comment]
Thank you for reporting @swertz , I have just created a PR with a fix.

**Comment by swertz** [comment]
Thanks for the quick fix @etejedor !
