### ISSUE TITLE
PyROOT endian issues on s390x

### ISSUE THREAD

**Issue by ellert** [root-project/root#12429]
- [x] Checked for duplicates

### Describe the bug

PyROOT related failures on s390x. Endian issus.

### Expected behavior

PyROOT should work on big endian without glitches.

### To Reproduce

1. Build root 6.28.00 for s390x
2. run unut tests

### Setup

1. ROOT version: 6.28.00
2. Fedora Linux s390x, RHEL+EPEL s390x
3. Compilation from source

### Additional context

The failing tests.

#### pyunittests-pyroot-pyz-rtensor 

This is an endian issue:

$ printf '%08x\n%08x\n' 16777216 1
01000000
00000001
~~~
 109/1272 Test   #62: pyunittests-pyroot-pyz-rtensor ......................................***Failed    2.92 sec
test_memoryAdoption (rtensor.ArrayInterface.test_memoryAdoption)
Test correct adoption of different datatypes ... ok
test_memoryLayout (rtensor.ArrayInterface.test_memoryLayout)
Test adoption of the memory layout ... ok
test_ownData (rtensor.ArrayInterface.test_ownData)
Test ownership of adopted numpy array ... ok
test_dtypes (rtensor.AsRTensor.test_dtypes)
Test adoption of numpy arrays with different data types ... ok
test_memoryLayout (rtensor.AsRTensor.test_memoryLayout)
Test adoption of the memory layout ... FAIL
test_strides (rtensor.AsRTensor.test_strides)
Test adoption of the strides ... ok
test_expandDims (rtensor.NumpyCompliance.test_expandDims)
Test np.expand_dims vs RTensor::ExpandDims ... ok
test_reshape (rtensor.NumpyCompliance.test_reshape)
Test np.reshape vs RTensor::Reshape ... FAIL
test_slice (rtensor.NumpyCompliance.test_slice)
Test slicing operations ... ok
test_squeeze (rtensor.NumpyCompliance.test_squeeze)
Test np.squeeze vs RTensor::Squeeze ... ok
test_transpose (rtensor.NumpyCompliance.test_transpose)
Test np.transpose vs RTensor::Transpose ... FAIL
======================================================================
FAIL: test_memoryLayout (rtensor.AsRTensor.test_memoryLayout)
Test adoption of the memory layout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/root-6.28.00/bindings/pyroot/pythonizations/test/rtensor.py", line 42, in test_memoryLayout
    self.assertEqual(root_obj.GetMemoryLayout(), 1)
AssertionError: 16777216 != 1
======================================================================
FAIL: test_reshape (rtensor.NumpyCompliance.test_reshape)
Test np.reshape vs RTensor::Reshape
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/root-6.28.00/bindings/pyroot/pythonizations/test/rtensor.py", line 218, in test_reshape
    self.assertEqual(x.GetMemoryLayout(), 1)
AssertionError: 16777216 != 1
======================================================================
FAIL: test_transpose (rtensor.NumpyCompliance.test_transpose)
Test np.transpose vs RTensor::Transpose
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/root-6.28.00/bindings/pyroot/pythonizations/test/rtensor.py", line 151, in test_transpose
    self.assertEqual(x.GetMemoryLayout(), 1)
AssertionError: 16777216 != 1
----------------------------------------------------------------------
Ran 11 tests in 2.036s
FAILED (failures=3)
CMake Error at /builddir/build/BUILD/root-6.28.00/cmake/modules/RootTestDriver.cmake:232 (message):
  error code: 1
~~~

#### pyunittests-pyroot-pyz-stl-vector
~~~
  61/1272 Test   #18: pyunittests-pyroot-pyz-stl-vector ...................................***Failed    0.84 sec
test_vec_char_data (stl_vector.STL_vector.test_vec_char_data)
Test that calling std::vector<char>::data() returns a Python string ... FAIL
test_vec_const_char_p (stl_vector.STL_vector.test_vec_const_char_p)
Test that creating a std::vector<const char*> does not raise any ... ok
======================================================================
FAIL: test_vec_char_data (stl_vector.STL_vector.test_vec_char_data)
Test that calling std::vector<char>::data() returns a Python string
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/root-6.28.00/bindings/pyroot/pythonizations/test/stl_vector.py", line 19, in test_vec_char_data
    self.assertEqual(v.data(), ''.join(elems))
AssertionError: '' != 'abc'
+ abc
----------------------------------------------------------------------
Ran 2 tests in 0.174s
FAILED (failures=1)
CMake Error at /builddir/build/BUILD/root-6.28.00/cmake/modules/RootTestDriver.cmake:232 (message):
  error code: 1
~~~

#### tutorial-dataframe-df006_ranges-py

TypeError: none of the 2 overloaded methods succeeded.
~~~
1096/1272 Test #1098: tutorial-dataframe-df006_ranges-py ..................................***Failed    7.50 sec
Traceback (most recent call last):
  File "/builddir/build/BUILD/root-6.28.00/tutorials/dataframe/df006_ranges.py", line 44, in <module>
    d_15_end_3 = d.Range(15, 0, 3)
                 ^^^^^^^^^^^^^^^^^
TypeError: none of the 2 overloaded methods succeeded. Full details:
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RRange<ROOT::Detail::RDF::RLoopManager>,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Range(unsigned int end) =>
    TypeError: takes at most 1 arguments (3 given)
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RRange<ROOT::Detail::RDF::RLoopManager>,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Range(unsigned int begin, unsigned int end, unsigned int stride = 1) =>
    runtime_error: Range: stride must be strictly greater than 0 and end must be greater than begin.
CMake Error at /builddir/build/BUILD/root-6.28.00/redhat-linux-build/RootTestDriver.cmake:232 (message):
  error code: 1
~~~

#### tutorial-fit-combinedFit-py

cppyy.gbl.std.out_of_range: none of the 2 overloaded methods succeeded.
~~~
1110/1272 Test #1115: tutorial-fit-combinedFit-py .........................................***Failed    1.71 sec
Traceback (most recent call last):
  File "/builddir/build/BUILD/root-6.28.00/tutorials/fit/combinedFit.py", line 98, in <module>
    fitter.Config().ParSettings(4).Fix()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cppyy.gbl.std.out_of_range: none of the 2 overloaded methods succeeded. Full details:
  const ROOT::Fit::ParameterSettings& ROOT::Fit::FitConfig::ParSettings(unsigned int i) =>
    out_of_range: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
  ROOT::Fit::ParameterSettings& ROOT::Fit::FitConfig::ParSettings(unsigned int i) =>
    out_of_range: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
CMake Error at /builddir/build/BUILD/root-6.28.00/redhat-linux-build/RootTestDriver.cmake:232 (message):
  error code: 1
~~~

#### tutorial-math-exampleFunction-py

ReferenceError: attempt to access a null-pointer
~~~
1132/1272 Test #1132: tutorial-math-exampleFunction-py ....................................***Failed  Error regular expression found in output. Regex=[Error in]  2.11 sec
Error in <ROOT::Math::Fitter::SetFCN>: FCN function has zero parameters 
Use Functor1D for wrapping one-dimensional function and compute integral of f(x) = x^2-1
integral-1D value =  5.999999999999999
Use Functor for wrapping a multi-dimensional function, the Rosenbrock Function r(x,y) and find its minimum
Traceback (most recent call last):
  File "/builddir/build/BUILD/root-6.28.00/tutorials/math/exampleFunction.py", line 57, in <module>
    fitter.Result().Print(ROOT.std.cout)
ReferenceError: attempt to access a null-pointer
CMake Error at /builddir/build/BUILD/root-6.28.00/redhat-linux-build/RootTestDriver.cmake:232 (message):
  error code: 1
~~~

#### tutorial-tmva-TMVA_CNN_Classification-py

There are probably 6 thread, not 25769803776. (Zero-extended from 32 to 64 bits in the wrong direction.)

$ printf '%016x\n' 25769803776
0000000600000000

TypeError: none of the 3 overloaded methods succeeded.
~~~
1270/1272 Test #1267: tutorial-tmva-TMVA_CNN_Classification-py ............................***Failed    1.33 sec
TMVA_CNN_Classificaton:0: RuntimeWarning: Skip using Keras since tensorflow is not installed
TMVA_CNN_Classificaton:0: RuntimeWarning: Skip using PyTorch since torch is not installed
DataSetInfo              : [dataset] : Added class "Signal"
                         : Add Tree sig_tree of type Signal with 1000 events
DataSetInfo              : [dataset] : Added class "Background"
                         : Add Tree bkg_tree of type Background with 1000 events
<FATAL>                         : Unknown method index in map: 0
***> abort program execution
Running with nthreads  =  25769803776
Traceback (most recent call last):
  File "/builddir/build/BUILD/root-6.28.00/tutorials/tmva/TMVA_CNN_Classification.py", line 299, in <module>
    factory.BookMethod(
  File "/builddir/build/BUILD/root-6.28.00/redhat-linux-build/lib/ROOT/_pythonization/_tmva/_factory.py", line 61, in BookMethod
    return self._BookMethod(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: none of the 3 overloaded methods succeeded. Full details:
  TMVA::MethodBase* TMVA::Factory::BookMethod(TMVA::DataLoader* loader, TString theMethodName, TString methodTitle, TString theOption = "") =>
    TypeError: could not convert argument 2
  TMVA::MethodBase* TMVA::Factory::BookMethod(TMVA::DataLoader* loader, TMVA::Types::EMVA theMethod, TString methodTitle, TString theOption = "") =>
    runtime_error: FATAL error
  TMVA::MethodBase* TMVA::Factory::BookMethod(TMVA::DataLoader*, TMVA::Types::EMVA, TString, TString, TMVA::Types::EMVA, TString) =>
    TypeError: takes at least 6 arguments (4 given)
CMake Error at /builddir/build/BUILD/root-6.28.00/redhat-linux-build/RootTestDriver.cmake:232 (message):
  error code: 1
~~~

#### tutorial-tmva-TMVA_Higgs_Classification-py

TypeError: none of the 3 overloaded methods succeeded.
~~~
1271/1272 Test #1268: tutorial-tmva-TMVA_Higgs_Classification-py ..........................***Failed    1.36 sec
TMVA_Higgs_Classification:0: RuntimeWarning: Skip using Keras since tensorflow is not available
Info in <TMVA_Higgs_Classification>: Download Higgs_data.root file
Info in <TFile::OpenFromCache>: using local cache copy of http://root.cern.ch/files/Higgs_data.root [./files/Higgs_data.root]
******************************************************************************
*Tree    :sig_tree  : tree                                                   *
*Entries :    10000 : Total =         1177229 bytes  File  Size =     785298 *
*        :          : Tree compression factor =   1.48                       *
******************************************************************************
*Br    0 :Type      : Type/F                                                 *
*Entries :    10000 : Total  Size=      40556 bytes  File Size  =        307 *
*Baskets :        1 : Basket Size=    1500672 bytes  Compression= 130.54     *
*............................................................................*
[ --- ]
*............................................................................*
*Br   28 :m_wwbb    : m_wwbb/F                                               *
*Entries :    10000 : Total  Size=      40566 bytes  File Size  =      34410 *
*Baskets :        1 : Basket Size=    1500672 bytes  Compression=   1.16     *
*............................................................................*
DataSetInfo              : [dataset] : Added class "Signal"
                         : Add Tree sig_tree of type Signal with 10000 events
DataSetInfo              : [dataset] : Added class "Background"
                         : Add Tree bkg_tree of type Background with 10000 events
<FATAL>                         : Unknown method index in map: 0
***> abort program execution
Traceback (most recent call last):
  File "/builddir/build/BUILD/root-6.28.00/tutorials/tmva/TMVA_Higgs_Classification.py", line 141, in <module>
    factory.BookMethod(
  File "/builddir/build/BUILD/root-6.28.00/redhat-linux-build/lib/ROOT/_pythonization/_tmva/_factory.py", line 61, in BookMethod
    return self._BookMethod(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: none of the 3 overloaded methods succeeded. Full details:
  TMVA::MethodBase* TMVA::Factory::BookMethod(TMVA::DataLoader* loader, TString theMethodName, TString methodTitle, TString theOption = "") =>
    TypeError: could not convert argument 2
  TMVA::MethodBase* TMVA::Factory::BookMethod(TMVA::DataLoader* loader, TMVA::Types::EMVA theMethod, TString methodTitle, TString theOption = "") =>
    runtime_error: FATAL error
  TMVA::MethodBase* TMVA::Factory::BookMethod(TMVA::DataLoader*, TMVA::Types::EMVA, TString, TString, TMVA::Types::EMVA, TString) =>
    TypeError: takes at least 6 arguments (4 given)
CMake Error at /builddir/build/BUILD/root-6.28.00/redhat-linux-build/RootTestDriver.cmake:232 (message):
  error code: 1
~~~

#### tutorial-tmva-TMVA_RNN_Classification-py

TypeError: none of the 3 overloaded methods succeeded.
~~~
1272/1272 Test #1269: tutorial-tmva-TMVA_RNN_Classification-py ............................***Failed    1.39 sec
Warning in <TMVA_RNN_Classificaton>: Skip using Keras since tensorflow is not installed
Warning in <TMVA_RNN_Classification>: TMVA is not build with GPU or CPU multi-thread support. Cannot use TMVA Deep Learning for RNN
DataSetInfo              : [dataset] : Added class "Signal"
                         : Add Tree sgn of type Signal with 2000 events
DataSetInfo              : [dataset] : Added class "Background"
                         : Add Tree bkg of type Background with 2000 events
<FATAL>                         : Unknown method index in map: 0
***> abort program execution
Running with nthreads  = 25769803776
--- RNNClassification  : Using input file: time_data_t10_d30.root
number of variables is 300
vars_time0[0]
[ --- ]
vars_time9[29]
prepared DATA LOADER 
Traceback (most recent call last):
  File "/builddir/build/BUILD/root-6.28.00/tutorials/tmva/TMVA_RNN_Classification.py", line 331, in <module>
    factory.BookMethod(
  File "/builddir/build/BUILD/root-6.28.00/redhat-linux-build/lib/ROOT/_pythonization/_tmva/_factory.py", line 61, in BookMethod
    return self._BookMethod(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: none of the 3 overloaded methods succeeded. Full details:
  TMVA::MethodBase* TMVA::Factory::BookMethod(TMVA::DataLoader* loader, TString theMethodName, TString methodTitle, TString theOption = "") =>
    TypeError: could not convert argument 2
  TMVA::MethodBase* TMVA::Factory::BookMethod(TMVA::DataLoader* loader, TMVA::Types::EMVA theMethod, TString methodTitle, TString theOption = "") =>
    runtime_error: FATAL error
  TMVA::MethodBase* TMVA::Factory::BookMethod(TMVA::DataLoader*, TMVA::Types::EMVA, TString, TString, TMVA::Types::EMVA, TString) =>
    TypeError: takes at least 6 arguments (4 given)
CMake Error at /builddir/build/BUILD/root-6.28.00/redhat-linux-build/RootTestDriver.cmake:232 (message):
  error code: 1
~~~

**Comment by ferdymercury** [comment]
Are less tutorials failing in https://github.com/root-project/root/issues/10409#issuecomment-2987483250 than here? Please reopen if these ones are still relevant and are not part of the other Issue.
