### ISSUE TITLE
Cppyy user-side breaks ROOT

### ISSUE THREAD

**Issue by adriansev** [root-project/root#12635]
### Explain what you would like to see improved
Installing a user-side cppyy (no virtualenv) breaks the python based ROOT tools.
So, i would like to be possible to have a user installed cppyy without this having an impact on ROOT installation

### Optional: share how it could be improved
 i was wondering if, given the special local only usage of a private/local version of cppyy, if this could be encapsulated somehow, so ROOT would use only it’s own version in such a way that is does not see any other cppyy version (even if discovered), and also the private cppyy modules are put in a place that would not be seen by anything outside ROOT as it’s not usable anyway:
```
[Thursday 06.04.23 21:38 adrian@hal] ~ $
python3
Python 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cppyy
/usr/lib64/python3.11/site-packages/cppyy_backend/loader.py:90: UserWarning: No precompiled header available (/usr/lib64/python3.11/site-packages/cppyy_backend/etc not writable); this may impact performance.
  warnings.warn('No precompiled header available (%s); this may impact performance.' % msg)
/usr/lib64/python3.11/site-packages/cppyy/__init__.py:266: UserWarning: CPyCppyy API path not found (tried: /usr/include); set CPPYY_API_PATH to fix
  warnings.warn("CPyCppyy API path not found (tried: %s); set CPPYY_API_PATH to fix" % os.path.dirname(cpycppyy_path))
```

### To Reproduce
```
rootls
usage: rootls [-h] [-1] [-l] [-t] FILE [FILE ...]
rootls: error: the following arguments are required: FILE

pip3 install --user cppyy

rootls
Traceback (most recent call last):
  File "/usr/bin/rootls", line 12, in <module>
    import cmdLineUtils
  File "/usr/share/root/cli/cmdLineUtils.py", line 81, in <module>
    import ROOT
  File "/usr/lib64/python3.11/site-packages/ROOT/__init__.py", line 25, in <module>
    cppyy.gbl.gROOT.SetBatch(False)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TROOT' object has no attribute 'SetBatch'. Did you mean: 'GetPath'?
```

### Setup
1.
```
root-config --version
6.26/10
```

2. Fedora 37

3. dnf install

1st posted in root-forum: https://root-forum.cern.ch/t/cppyy-user-side-breaks-root/54393

**Comment by guitargeek** [comment]
Thanks for opening this issue! We need @vepadulano to take a look when he's back. On my side I can also recreate the crash on Arch Linux:
```
pacman -S root
pip install --user cppyy
python -c "import ROOT" 
```

**Comment by dpiparo** [comment]
Is this still the case after the upgrade?

**Comment by guitargeek** [comment]
Hi @dpiparo and thanks a lot @adriansev for this useful report!

Yes, there is probably even more breakage than before now that the `cppyy` in ROOT is synced more with `cppyy` upstream. More files are expected to collide. The cppyy module is part of ROOT, and if you install it in two different ways in the same environment (standalone and via ROOT), clashes are bound to happen.

So the question to @adriansev is really: what's your usecase for installing cppyy in two different ways in the same environment? What does cppyy standalone give you that you won't get with ROOT? And why is the recommended way of dealing with this (virtual environments) not an option for you?

Many Linux distributions even *force* you to use virtual environments and don't allow `pip install --user` outside of virtual environments anymore. E.g. Arch, NixOS, or Ubuntu:
  * https://askubuntu.com/questions/1465218/pip-error-on-ubuntu-externally-managed-environment-%C3%97-this-environment-is-extern

So given that your usecase is against good practices and that it's expected that if you install the same library from two different sources you get breakage, I'm in favor of closing this as "not planned" unless @adriansev can follow up with a clear motivation :slightly_smiling_face:

**Comment by adriansev** [comment]
@guitargeek starting with the end: yes, you can close this as indeed the standard solution is to have venvs. but the reason that i hit this was only the laziness to have a venv specifically for this :) and the goal to a have a project dependent only on cppyy not on ROOT (it would be to much to use ROOT only for cppyy). Thanks a lot!

**Comment by aaronj0** [comment]
Closing as the recommended workaround for this use case is using virtual environments, to prevent clashes in the modules

**Comment by ikrommyd** [comment]
I'm hitting this right now. A conda installation of root + cppyy (either from conda-forge or even pypi) is segfaulting.
I'm on macos arm64 and I made an env with `mamba create -n tmp root_base cppyy python=3.13`

Just trying to import ROOT in python will give you a seg fault. I don't see how "just switch environments if you wanna use cppyy" is satisfactory here. Is there something that can be done here? I can open a new issue or bring it up to the ROOT forum too in order for this to be tracked.

My vague understanding is that ROOT vendors cppyy and will put `.so` files in the environment which conflict with the files cppyy provides.
```
awkward-coffea) ➜  ~ python
Python 3.13.7 | packaged by conda-forge | (main, Sep  3 2025, 14:24:46) [Clang 19.1.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
 *** Break *** segmentation violation
[/Users/iason/micromamba/envs/awkward-coffea/lib/libcppyy_backend.6.36.04.so] (anonymous namespace)::TExceptionHandlerImp::HandleException(int) (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/lib/libCore.6.36.04.so] TUnixSystem::DispatchSignals(ESignals) (no debug info)
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/lib/libcppyy.6.36.04.so] CPyCppyy::CreateScopeProxy(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, _object*, unsigned int) (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/lib/python3.13/site-packages/libROOTPythonizations.so] PyInit_libROOTPythonizations (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyImport_RunModInitFunc (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] import_run_extension (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _imp_create_dynamic (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] cfunction_vectorcall_FASTCALL (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyEval_EvalFrameDefault (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] object_vacall (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyObject_CallMethodObjArgs (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyImport_ImportModuleLevelObject (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyEval_EvalFrameDefault (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyEval_EvalCode (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] builtin_exec (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] cfunction_vectorcall_FASTCALL_KEYWORDS (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyEval_EvalFrameDefault (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] object_vacall (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyObject_CallMethodObjArgs (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyImport_ImportModuleLevelObject (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyEval_EvalFrameDefault (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyEval_EvalCode (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] builtin_exec (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] cfunction_vectorcall_FASTCALL_KEYWORDS (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyObject_Vectorcall (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyEval_EvalFrameDefault (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyEval_EvalCode (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] builtin_exec (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] cfunction_vectorcall_FASTCALL_KEYWORDS (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyObject_Vectorcall (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyEval_EvalFrameDefault (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] pymain_run_module (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] pymain_run_stdin (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] Py_RunMain (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] pymain_main (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] main (no debug info)
[/usr/lib/dyld] start (no debug info)
 *** Break *** segmentation violation
[/Users/iason/micromamba/envs/awkward-coffea/lib/libcppyy_backend.6.36.04.so] (anonymous namespace)::TExceptionHandlerImp::HandleException(int) (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/lib/libCore.6.36.04.so] TUnixSystem::DispatchSignals(ESignals) (no debug info)
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/lib/libcppyy.6.36.04.so] CPyCppyy::CreateScopeProxy(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, _object*, unsigned int) (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/lib/python3.13/site-packages/libROOTPythonizations.so] PyInit_libROOTPythonizations (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyImport_RunModInitFunc (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] import_run_extension (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _imp_create_dynamic (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] cfunction_vectorcall_FASTCALL (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyEval_EvalFrameDefault (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] object_vacall (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyObject_CallMethodObjArgs (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyImport_ImportModuleLevelObject (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyEval_EvalFrameDefault (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyEval_EvalCode (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] builtin_exec (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] cfunction_vectorcall_FASTCALL_KEYWORDS (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyEval_EvalFrameDefault (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] object_vacall (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyObject_CallMethodObjArgs (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyImport_ImportModuleLevelObject (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyEval_EvalFrameDefault (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyEval_EvalCode (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] builtin_exec (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] cfunction_vectorcall_FASTCALL_KEYWORDS (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyObject_Vectorcall (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyEval_EvalFrameDefault (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyEval_EvalCode (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] builtin_exec (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] cfunction_vectorcall_FASTCALL_KEYWORDS (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] PyObject_Vectorcall (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] _PyEval_EvalFrameDefault (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] pymain_run_module (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] pymain_run_stdin (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] Py_RunMain (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] pymain_main (no debug info)
[/Users/iason/micromamba/envs/awkward-coffea/bin/python3.13] main (no debug info)
[/usr/lib/dyld] start (no debug info)
```

**Comment by guitargeek** [comment]
Hi @ikrommyd, thanks for reporting!

ROOT already includes a version of cppyy, so by installing also a cppyy package at the same time your are touching the same files and make your environment inconsistent.

If you want to use `cppyy` and ROOT, just install ROOT only. You can do `import cppyy` as well. The `cppyy` version in ROOT varies from upstream cppyy, but not that much. You'll probably not notice it in 95 % of use cases.

In any case, using ROOT and upstream cppyy at the same time would not work anyway - even if the file collisions are fixed -, because of the different versions of Cling. I'm pretty sure things go wrong when you have 2 Cling libraries loaded at the same time.

If you want to use just `cppyy`, then don't install the ROOT package at the same time.

Or is using `cppyy` shipped by ROOT not an option for some specific reason?

**Comment by ikrommyd** [comment]
Hi @guitargeek, thanks for the response. Yeah Vincenzo let me know offline on Slack that you can use the `cppyy` that comes with ROOT and that this "conflict" is expected behavior at the moment and using the `cppyy` that comes with ROOT is the proposed solution and that's fine as long as users can have some kind of cppyy access in the environment 😄.

I'm noticing however some differences in how the two `cppyy` versions parse a header file in the sense that the python objects they expose to the interpreter behave slightly different. I will open a separate issue for this though. Thanks!
