### ISSUE TITLE
Dictionary generation confused by anonymous enums.

### ISSUE THREAD

**Issue by pcanal** [root-project/root#12953]
### Describe the bug

Using:
[hep3vec.tar.gz](https://github.com/root-project/root/files/11658469/hep3vec.tar.gz)
we get:
```
. ./go

StreamerInfo for class: Hep3Vec, version=1, checksum=0x0
Error in <TProtoClass::FindDataMember>: data member with index 0 is not found in class Hep3Vec
Error in <CreateRealData>: Cannot find data member # 0 of class Hep3Vec for parent Holder!
```
which is cause by the `TClass` (for the class enclosing the anonymous enum) being created during the reading of the rootpcm **before** its own `TProtoClass` is fully loaded (actually during its loading).
```
#7  0x00007ffff7784e29 in TClass::GetClass (name=0x7fffffff9ec0 "Hep3Vec", load=true, silent=false) at /nashome/p/pcanal/root/core/meta/src/TClass.cxx:2970
...
#9  0x00007ffff77a7c80 in TEnum::GetEnum (enumName=0xf5c810 "Hep3Vec::(unnamed)", sa=TEnum::kInterpLookup) at /nashome/p/pcanal/root/core/meta/src/TEnum.cxx:310
#10 0x00007ffff77a0150 in TDataMember::Init (this=0xf5c6d0, afterReading=true) at /nashome/p/pcanal/root/core/meta/src/TDataMember.cxx:225
#11 0x00007ffff77a3606 in TDataMember::Streamer (this=0xf5c6d0, b=...) at /nashome/p/pcanal/root/core/meta/src/TDataMember.cxx:949
....
#27 0x00007ffff763e5ed in TProtoClass::Streamer (this=0xf5c0e0, R__b=...) at core/G__Core.cxx:26439
....
#38 0x00007fffeab11c72 in TCling::LoadPCM (this=0x738b90, pcmFileNameFullPath=...) at /nashome/p/pcanal/root/core/metacling/src/TCling.cxx:1906


### What is the expected behaviour?

properly loading of the dictionary

### How to reproduce?

Use [hep3vec.tar.gz](https://github.com/root-project/root/files/11658469/hep3vec.tar.gz)
and run `go`

### ROOT version

work in progress ... 

### How did you install ROOT?

local build

### Which operating system are you using?

alll

### Additional context

_No response_

**Comment by pcanal** [comment]
nevermind ... this was against work-in-progress code attempting to improve the detection of the underlying type of an enum.
