### ISSUE TITLE
Cannot use range-v3 in the interpreter with C++20 enabled

### ISSUE THREAD

**Issue by pikacic** [root-project/root#13001]
### Check duplicate issues.

- [X] Checked for duplicates

### Describe the bug

Because of the implicit `using namespace std` in the interpreter, trying to use range-v3 headers result in errors about ambiguous references, like:
```
In file included from ROOT_prompt_0:1:
In file included from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-el9-gcc13-dbg/include/range/v3/range/traits.hpp:24:
In file included from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-el9-gcc13-dbg/include/range/v3/range_fwd.hpp:23:
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-el9-gcc13-dbg/include/concepts/compare.hpp:35:39: error: reference to 'ranges' is ambiguous
        concept compares_as = same_as<ranges::common_comparison_category_t<T, Cat>, Cat>;
                                      ^
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-el9-gcc13-dbg/include/range/v3/compare.hpp:25:11: note: candidate found by name lookup is 'ranges'
namespace ranges
          ^
/cvmfs/sft.cern.ch/lcg/releases/gcc/13.1.0-b3d18/x86_64-el9/include/c++/13.1.0/experimental/string_view:689:13: note: candidate found by name lookup is 'std::ranges'
  namespace ranges
            ^
```

### What is the expected behaviour?

I expect to be able to use the top level `ranges` namespace at the same time as `std::ranges`.

### How to reproduce?

From lxplus9.cern.ch
```
❯ . /cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-el9-gcc13-dbg/setup.sh
❯ root
   ------------------------------------------------------------------
  | Welcome to ROOT 6.28/05                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jun 10 2023, 00:28:00                 |
  | From heads/v6-28-00-patches@v6-28-04-94-gb7de1efc73              |
  | With g++ (GCC) 13.1.0                                            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] #include <range/v3/range/traits.hpp>
In file included from ROOT_prompt_0:1:
In file included from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-el9-gcc13-dbg/include/range/v3/range/traits.hpp:24:
In file included from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-el9-gcc13-dbg/include/range/v3/range_fwd.hpp:23:
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-el9-gcc13-dbg/include/concepts/compare.hpp:35:39: error: reference to 'ranges' is ambiguous
        concept compares_as = same_as<ranges::common_comparison_category_t<T, Cat>, Cat>;
                                      ^
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-el9-gcc13-dbg/include/range/v3/compare.hpp:25:11: note: candidate found by name lookup is 'ranges'
namespace ranges
          ^
/cvmfs/sft.cern.ch/lcg/releases/gcc/13.1.0-b3d18/x86_64-el9/include/c++/13.1.0/experimental/string_view:689:13: note: candidate found by name lookup is 'std::ranges'
  namespace ranges
            ^
```

### ROOT version

v6-28-00-patches

### How did you install ROOT?

LCG nightly builds in /cvmfs/sft-nightlies.cern.ch

### Which operating system are you using?

Linux Alma 9

### Additional context

I wanted to report this problem as a compelling use case that requires #11027

**Comment by pcanal** [comment]
As a side note, the error mentions:
```
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-el9-gcc13-dbg/include/concepts/compare.hpp:35:39: error: reference to 'ranges' is ambiguous
        concept compares_as = same_as<ranges::common_comparison_category_t<T, Cat>, Cat>;
                                      ^
```

Shouldn't this header file _also_ be improved by fully qualifying ranges here? (i.e. would the same problem happens in a compilation unit where the user of this header and `string_view` want to use `using namespace std;`?

**Comment by pikacic** [comment]
Yes, of course, I can reproduce the error in regular C++ with something as simple as <https://godbolt.org/z/rnqWer3bj>:
```cpp
#include <ranges>
using namespace std;
#include <range/v3/views.hpp>
```
but I see 2 errors in this example:
- using std::ranges and ranges at the same time (not really an error, but a bit silly)
- `using namespace std` before including `range/v3/views.hpp` (actually `using namespace std` should be considered an error by itself).

The following code works:
```cpp
#include <ranges>
#include <range/v3/views.hpp>
using namespace std;
```
still a bit silly, but it works.

So, I'm sorry, but I do not buy the comment that developers of libraries should always put `::` in front of every top level namespace. I believe it is fairy reasonable to assume that nobody does `using namespace std;` before including any header.

**Comment by pcanal** [comment]
Yes, it is still true that we need to remove/replace the `using namespace` and it is also true that making one's own headers more resilient to silly but legal usage is usually worth the slight (and debatable) decrease in readability (by having/adding more qualification).

**Comment by guitargeek** [comment]
This was mentioned recently again on the forum:
https://root-forum.cern.ch/t/precompiled-root-broke-after-installing-librange-v3-dev-on-ubuntu/61603

**Comment by ferdymercury** [comment]
Still an issue in master / Ubu22 and with LLVM20. EDIT: And on Ubu24 with LLVM22 it crashes when including the header

sudo apt install librange-v3-dev
root

---> Crashes
`root.exe: /opt/root_src/interpreter/llvm-project/clang/lib/Serialization/ASTReader.cpp:4332: clang::ASTReader::ASTReadResult clang::ASTReader::ReadModuleMapFileBlock(clang::ASTReader::RecordData&, clang::ASTReader::ModuleFile&, const ModuleFile*, unsigned int): Assertion M && M->Name == F.ModuleName && "found module with different name"' failed.`

or with binary build:
```
input_line_1:1:2: fatal error: module file '/github/home/ROOT-CI/build/lib/libc.pcm' not found: module file not found
#include <new>
 ^
input_line_1:1:2: note: imported by module 'std' in '/opt/root/lib/std.pcm'
Warning in cling::IncrementalParser::CheckABICompatibility():
  Failed to extract C++ standard library version.
Module libc not found.
Failed to load module std
<<< cling interactive line includer >>>: fatal error: module file '/github/home/ROOT-CI/build/lib/libc.pcm' not found: module file not found
<<< cling interactive line includer >>>: note: imported by module '_Builtin_intrinsics' in '/opt/root/lib/_Builtin_intrinsics.pcm'

#5  <signal handler called>
#6  0x00007e1010fcd3c0 in ROOT::TMetaUtils::TNormalizedCtxtImpl::keepTypedef(cling::LookupHelper const&, char const*, bool) () from /opt/root/lib/libCling.so
#7  0x00007e1010fcd785 in ROOT::TMetaUtils::TNormalizedCtxtImpl::TNormalizedCtxtImpl(cling::LookupHelper const&) () from /opt/root/lib/libCling.so
#8  0x00007e1010fcdef6 in ROOT::TMetaUtils::TNormalizedCtxt::TNormalizedCtxt(cling::LookupHelper const&) () from /opt/root/lib/libCling.so
#9  0x00007e10110b3c25 in TCling::TCling(char const*, char const*, char const* const*, void*) () from /opt/root/lib/libCling.so
#10 0x00007e10110b5798 in CreateInterpreter () from /opt/root/lib/libCling.so
#11 0x00007e10184028b3 in TROOT::InitInterpreter() () from /opt/root/lib/libCore.so
#12 0x00007e1018402daf in ROOT::Internal::GetROOT2() () from /opt/root/lib/libCore.so
#13 0x00007e10183acf4d in TApplication::TApplication(char const*, int*, char**, void*, int) () from /opt/root/lib/libCore.so
#14 0x00007e10188be340 in TRint::TRint(char const*, int*, char**, void*, int, bool, bool) () from /opt/root/lib/libRint.so
#15 0x00005da6b34532e7 in main ()
```
Surprising by the way that the binary build tries to look for hard-coded path '/github/home/ROOT-CI/build/lib/libc.pcm' not found
