### ISSUE TITLE
Cleaner stack traces in python

### ISSUE THREAD

**Issue by dguest** [root-project/root#14097]
### Explain what you would like to see improved and how.

I'd like my stack traces to be just as readable with and without ROOT imported.

If I do
```python
import ROOT
from zork import dork
```
I get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "path/to/ROOT/_facade.py", line 154, in _importhook
    return _orig_ihook(name, *args, **kwds)
ModuleNotFoundError: No module named 'zork'
```
Whereas without this I just get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'zork'
```

This on its own isn't bad, but when it's a deeply nested exception I get the ROOT `_importhook` thing for every frame. Unfortunately most ATLAS code ends up with `import ROOT` somewhere after it gets big enough.

### ROOT version

LCG_104b_ATLAS_3/ROOT/6.28.08/x86_64-centos7-gcc11-opt

### Installation method

cvmfs

### Operating system

SC 7.9

**Comment by guitargeek** [comment]
Hello, thanks for the report! Would you be willing to trade the possibility to do `from ROOT.Foo import bar` against these side effects of import ROOT being gone? :)

This is what I would suggest:
  * https://github.com/root-project/root/pull/14098

**Comment by dguest** [comment]
I didn't even know about the other bug you point out there! But I agree that removing invisible state dependence in the imports would be very desirable. I don't want my code to stop working because someone deletes the orphaned `import ROOT` statement. We actually have linting in ATLAS that would complain about code which is written this way.

**Comment by guitargeek** [comment]
Ok! Well, the other "bug" was not an actual bug. Doing something like `from ROOT.Foo import Bar` is not expected to work when `Foo` is a C++ namespace. We just had this hack to kind of pretend that Cppyy namespaces are Python modules to enable this import syntax. But I don't think the benefit is big enough to justify things like `__builtin__.__import__ = _importhook`.

**Comment by chrisburr** [comment]
There is an alternative way to get this using meta path finders.

<details><summary>Click to show diff</summary>
<p>

This would need to be polished and checked that it actually follows the `Loader`/`MetaPathFinder` interface correctly but it shows the general idea:

```diff
diff --git a/bindings/pyroot/pythonizations/python/ROOT/__init__.py b/bindings/pyroot/pythonizations/python/ROOT/__init__.py
index 113e778cda..21c8aa7454 100644
--- a/bindings/pyroot/pythonizations/python/ROOT/__init__.py
+++ b/bindings/pyroot/pythonizations/python/ROOT/__init__.py
@@ -48,7 +48,65 @@ _is_ipython = hasattr(builtins, '__IPYTHON__')
 # Configure ROOT facade module
 import sys
 from ._facade import ROOTFacade
-sys.modules[__name__] = ROOTFacade(sys.modules[__name__], _is_ipython)
+xxx = ROOTFacade(sys.modules[__name__], _is_ipython)
+__getattr__ = xxx._getattr
+__setattr__ = xxx._setattr
+
+# Configure meta-path finder for ROOT namespaces
+import importlib.abc
+from importlib.util import spec_from_loader
+
+class RootNamespaceLoader(importlib.abc.Loader):
+    def __init__(self):
+        self._module_cache = {}
+
+    def is_package(self, fullname):
+        if fullname in self._module_cache:
+            return True
+        if not fullname.startswith("ROOT."):
+            raise ImportError("This loader only loads ROOT.*")
+        module = xxx
+        partial_name = "ROOT"
+        for part in fullname.split(".")[1:]:
+            partial_name += f".{part}"
+            module = getattr(module, part, None)
+            if module is None:
+                raise NotImplementedError(f"No module named {partial_name}")
+            # HACK: There is a probably a better way to do this
+            if "namespace" not in str(module):
+                raise ImportError(f"{partial_name} is not a namespace (type={type(module)})")
+        self._module_cache[fullname] = module
+        return True
+
+    def create_module(self, spec):
+        self.is_package(spec.name)
+        return self._module_cache[spec.name]
+
+    def exec_module(self, module):
+        pass
+
+    def load_module(self, fullname):
+        self.is_package(fullname)
+        return self._module_cache[fullname]
+
+
+class RootNamespaceFinder(importlib.abc.MetaPathFinder):
+    def __init__(self):
+        self.loader = RootNamespaceLoader()
+
+    def find_spec(self, fullname, path, target=None):
+        try:
+            self.loader.is_package(fullname)
+        except ImportError:
+            return None
+        return spec_from_loader(fullname, self.loader)
+
+    def invalidate_caches(self):
+        self.loader = RootNamespaceLoader()
+
+namespace_finder = RootNamespaceFinder()
+if namespace_finder not in sys.meta_path:
+    sys.meta_path.append(namespace_finder)

 # Configuration for usage from Jupyter notebooks
 if _is_ipython:
diff --git a/bindings/pyroot/pythonizations/python/ROOT/_facade.py b/bindings/pyroot/pythonizations/python/ROOT/_facade.py
index 69046fc71c..91e7732e5a 100644
--- a/bindings/pyroot/pythonizations/python/ROOT/_facade.py
+++ b/bindings/pyroot/pythonizations/python/ROOT/_facade.py
@@ -135,24 +135,7 @@ class ROOTFacade(types.ModuleType):
         return CreateBufferFromAddress(addr)

     def _set_import_hook(self):
-        # This hook allows to write e.g:
-        # from ROOT.A import a
-        # instead of the longer:
-        # from ROOT import A
-        # from A import a
-        try:
-            import __builtin__
-        except ImportError:
-            import builtins as __builtin__  # name change in p3
-        _orig_ihook = __builtin__.__import__
-        def _importhook(name, *args, **kwds):
-            if name[0:5] == 'ROOT.':
-                try:
-                    sys.modules[name] = getattr(self, name[5:])
-                except Exception:
-                    pass
-            return _orig_ihook(name, *args, **kwds)
-        __builtin__.__import__ = _importhook
+        pass

     def _handle_import_all(self):
         # Called if "from ROOT import *" is executed in the app.
```

</p>
</details> 

Before:

```bash
+ python -c 'from ROOT.Experimental import RCanvas; print(RCanvas)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ROOT.Experimental'; 'ROOT' is not a package

+ python -c 'import ROOT; print(ROOT.Experimental.RCanvas)'
<class cppyy.gbl.ROOT.Experimental.RCanvas at 0x55e53c0b4ab0>

+ python -c 'import ROOT; import missing_module'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cburr/miniconda3/envs/test/lib/python3.11/site-packages/ROOT/_facade.py", line 154, in _importhook
    return _orig_ihook(name, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'missing_module'
```

After:

```bash
+ python -c 'from ROOT.Experimental import RCanvas; print(RCanvas)'
<class cppyy.gbl.ROOT.Experimental.RCanvas at 0x555c9a1595a0>

+ python -c 'import ROOT; print(ROOT.Experimental.RCanvas)'
<class cppyy.gbl.ROOT.Experimental.RCanvas at 0x563ffa2c9780>

+ python -c 'import ROOT; import missing_module'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'missing_module'
```

**Comment by guitargeek** [comment]
Closed by:
  * https://github.com/root-project/root/pull/14098
