### ISSUE TITLE
roottest.root.hist.h2root Fails always on march=native builds and sporadically on all other platforms

### ISSUE THREAD

**Issue by pcanal** [root-project/root#14155]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

As seen in https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/190460/testReport/projectroot.roottest.root/hist/roottest_root_hist_h2root, `h2root` fails from time to time on Linux and always if the *march=native* option is active.

### Reproducer

```
-- TEST COMMAND -- 
cd /home/sftnight/build/workspace/root-pullrequests-build/build/roottest/root/hist
/usr/bin/timeout -s USR2 270s h2root mb4i1.hbook
-- BEGIN TEST OUTPUT --

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f55ea9f53ea in __GI___wait4 (pid=1686062, stat_loc=stat_loc
entry=0x7ffffe689758, options=options
entry=0, usage=usage
entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
#1  0x00007f55ea9f53ab in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc
entry=0x7ffffe689758, options=options
entry=0) at ./posix/waitpid.c:38
#2  0x00007f55ea95bbdb in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:171
#3  0x00007f55eb242bc4 in TUnixSystem::StackTrace() () from /home/sftnight/build/workspace/root-pullrequests-build/build/lib/libCore.so.6.31
#4  0x00007f55eb23fef5 in TUnixSystem::DispatchSignals(ESignals) () from /home/sftnight/build/workspace/root-pullrequests-build/build/lib/libCore.so.6.31
#5  <signal handler called>
#6  0x0000556fff8ce440 in mzlink_ ()
#7  0x0000556fff8be829 in hlimit_ ()
#8  0x0000556fff8ad586 in main ()
#9  0x00007f55ea934d90 in __libc_start_call_main (main=main
entry=0x556fff8ad4d0 <main>, argc=argc
entry=2, argv=argv
entry=0x7ffffe68cf78) at ../sysdeps/nptl/libc_start_call_main.h:58
#10 0x00007f55ea934e40 in __libc_start_main_impl (main=0x556fff8ad4d0 <main>, argc=2, argv=0x7ffffe68cf78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffffe68cf68) at ../csu/libc-start.c:392
#11 0x0000556fff8ad8b5 in _start ()
===========================================================


The lines below might hint at the cause of the crash. If you see question
marks as part of the stack trace, try to recompile with debugging information
enabled and export CLING_DEBUG=1 environment variable before running.
You may get help by asking at the ROOT forum https://root.cern/forum
preferably using the command (.forum bug) in the ROOT prompt.
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern/bugs or (preferably) using the command (.gh bug) in
the ROOT prompt. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x0000556fff8ce440 in mzlink_ ()
#7  0x0000556fff8be829 in hlimit_ ()
#8  0x0000556fff8ad586 in main ()
#9  0x00007f55ea934d90 in __libc_start_call_main (main=main
entry=0x556fff8ad4d0 <main>, argc=argc
entry=2, argv=argv
entry=0x7ffffe68cf78) at ../sysdeps/nptl/libc_start_call_main.h:58
#10 0x00007f55ea934e40 in __libc_start_main_impl (main=0x556fff8ad4d0 <main>, argc=2, argv=0x7ffffe68cf78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffffe68cf68) at ../csu/libc-start.c:392
#11 0x0000556fff8ad8b5 in _start ()
===========================================================



-- END TEST OUTPUT --
CMake Error at /home/sftnight/build/workspace/root-pullrequests-build/build/RootTestDriver.cmake:186 (message):
  got exit code 139 but expected 0
```

### ROOT version

master

### Installation method

Jenkins/CI

### Operating system

Ubuntu 22.04

**Comment by guitargeek** [comment]
That reminds me: we don't test the fortran features on the new CI! :warning:

**Comment by dpiparo** [comment]
Now we do it on Linux, but not on mac https://github.com/root-project/root/issues/15422 . It is at this point crucial to activate fortran on macs to let the CI verify whether we have a problem there or not (@couet )

**Comment by dpiparo** [comment]
we saw a failure in the CI https://github.com/root-project/root/actions/runs/9184221811/job/25256182955?pr=15597#step:9:6949
