### ISSUE TITLE
MIsbehaviour of ROOT with ASAN enabled: some tests are failing

### ISSUE THREAD

**Issue by dpiparo** [root-project/root#14682]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

ROOT misbehaves when ASAN is enabled. Below different incarnation of the problem are illustrated:
- [ ] root/io/bigevent, root/io/event, root/io/compression, root/io/datamodelevolution, root/io/perf, root/treeformula/event, root/treeformula/retobj, 
root/treeformula/schemaEvolution, root/treeformula/sync, root/tree/friend, root/tree/evolution, root/tree/treeproblem, root/treeproxy, root/io/compression : bad linkage to asan functions
- [ ] root/io/references:  badly setup dependency on libEvent
- [ ] root/tree/addresses : `AddressSanitizer: heap-buffer-overflow`
- [ ] root/io/newClassDef: Real failure with ASAN enabled
- [ ] root/io/cint: bad linkage to ASAN libraries. Should also check if the tests are needed at all

Moreover, the above (and root/tree/addresses) are automatic Makefile driven tests. They could be translated to CMake to gain granularity.

### Reproducer

Run with Asan

### ROOT version

master

### Installation method

From sources (need asan)

### Operating system

Linux, mac

**Comment by ferdymercury** [comment]
Cross-post from https://github.com/root-project/root/issues/19329

Adding -fsanitize undefined / address c++ flags to main/CMakeLists.txt (h2root) target, we get:
```

 /github/home/ROOT-CI/src/misc/minicern/src/cernlib.c:82:18: runtime error: left shift of negative value -2012982016
  /github/home/ROOT-CI/src/misc/minicern/src/cernlib.c:83:18: runtime error: left shift of negative value -2012982016
  /github/home/ROOT-CI/src/misc/minicern/src/cernlib.c:100:12: runtime error: left shift of 1212370737 by 8 places cannot be represented in type 'int'
  /github/home/ROOT-CI/src/misc/minicern/src/cernlib.c:100:39: runtime error: left shift of 1212370737 by 24 places cannot be represented in type 'int'
  /github/home/ROOT-CI/src/misc/minicern/src/zebra.f:6746:72: runtime error: load of address 0x5560461bae2c with insufficient space for an object of type 'integer(kind=4)'
  0x5560461bae2c: note: pointer points here
    24 02 00 00 18 2f 0f 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
                ^ 
  /github/home/ROOT-CI/src/misc/minicern/src/zebra.f:6747:72: runtime error: load of address 0x5560461bae2c with insufficient space for an object of type 'integer(kind=4)'
  0x5560461bae2c: note: pointer points here
    24 02 00 00 18 2f 0f 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
                ^ 
  /github/home/ROOT-CI/src/misc/minicern/src/zebra.f:6753:72: runtime error: store to address 0x5560461bae2c with insufficient space for an object of type 'integer(kind=4)'
  0x5560461bae2c: note: pointer points here
    24 02 00 00 18 2f 0f 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
                ^ 
```

from https://github.com/root-project/root/pull/18234

and also:

Very rarely (just once) I got this debug stacktrace (2158 in my debug build was at line NWTAB = IQ(KQS+LSYS+1)):

```
/opt/root_src/misc/minicern/src/zebra.f:2158:72: runtime error: load of address 0x64d8ffa72fc8 with insufficient space for an object of type 'integer(kind=4)'
0x64d8ffa72fc8: note: pointer points here



/opt/root_src/misc/minicern/src/zebra.f:2158:72: runtime error: load of address 0x64d8ffa72fc8 with insufficient space for an object of type 'integer(kind=4)'
0x64d8ffa72fc8: note: pointer points here
<memory cannot be printed>

 *** Break *** segmentation violation



===========================================================
There was a crash (kSigSegmentationViolation).
This is the entire stack trace of all threads:
===========================================================
#0  0x00007da33a6ea3ea in __GI___wait4 (pid=1162663, stat_loc=stat_loc
entry=0x7fff5a35ae28, options=options
entry=0, usage=usage
entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
#1  0x00007da33a6ea3ab in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc
entry=0x7fff5a35ae28, options=options
entry=0) at ./posix/waitpid.c:38
#2  0x00007da33a650bdb in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:171
#3  0x00007da33b366d5a in TUnixSystem::Exec (this=0x617000001200, shellcmd=0x60700026bc80 "/home/user/build/build-root-Desktop-Debug/etc/gdb-backtrace.sh 1162652 1>&2") at /opt/root_src/core/unix/src/TUnixSystem.cxx:2160
#4  0x00007da33b36767e in TUnixSystem::StackTrace (this=0x617000001200) at /opt/root_src/core/unix/src/TUnixSystem.cxx:2451
#5  0x00007da33b36b515 in TUnixSystem::DispatchSignals (this=0x617000001200, sig=kSigSegmentationViolation) at /opt/root_src/core/unix/src/TUnixSystem.cxx:3671
#6  0x00007da33b3626fe in SigHandler (sig=kSigSegmentationViolation) at /opt/root_src/core/unix/src/TUnixSystem.cxx:410
#7  0x00007da33b36b413 in sighandler (sig=11) at /opt/root_src/core/unix/src/TUnixSystem.cxx:3642
#8  <signal handler called>
#9  0x000064d7ff3a5020 in mzlink (ixstor=0, chname=..., larea=..., lref=..., lrefl=..., _chname=8) at /opt/root_src/misc/minicern/src/zebra.f:2158
#10 0x000064d7ff34b6d1 in hlimit (limit=4000000) at /opt/root_src/misc/minicern/src/hbook.f:206
#11 0x000064d7ff2f39eb in main (argc=2, argv=0x7fff5a35e838) at /opt/root_src/main/src/h2root.cxx:311
===========================================================


The lines below might hint at the cause of the crash. If you see question
marks as part of the stack trace, try to recompile with debugging information
enabled and export CLING_DEBUG=1 environment variable before running.
You may get help by asking at the ROOT forum https://root.cern/forum
preferably using the command (.forum bug) in the ROOT prompt.
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern/bugs or (preferably) using the command (.gh bug) in
the ROOT prompt. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#9  0x000064d7ff3a5020 in mzlink (ixstor=0, chname=..., larea=..., lref=..., lrefl=..., _chname=8) at /opt/root_src/misc/minicern/src/zebra.f:2158
#10 0x000064d7ff34b6d1 in hlimit (limit=4000000) at /opt/root_src/misc/minicern/src/hbook.f:206
#11 0x000064d7ff2f39eb in main (argc=2, argv=0x7fff5a35e838) at /opt/root_src/main/src/h2root.cxx:311
===========================================================


==1162752==Processing thread 1162652.
==1162752==Stack at 0x7fff59b61000-0x7fff5a361000 (SP = 0x7fff5a35cea8).
==1162752==TLS at 0x7da33ddf1000-0x7da33ddf7680.

```

**Comment by ferdymercury** [comment]
Related:

https://github.com/root-project/root/issues/7968
https://github.com/root-project/root/issues/8027
https://github.com/root-project/root/issues/15818

**Comment by ferdymercury** [comment]
Also: when building on Ubu22 with asan, I get:
See also: https://github.com/root-project/root/actions/runs/16941754812/job/48012438974?pr=19636

```
2025-08-13T17:08:43.1371694Z ==90460==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f112ba1c604 at pc 0x7f1104fcbd2b bp 0x7ffc5d872180 sp 0x7ffc5d872170
2025-08-13T17:08:43.1372343Z READ of size 4 at 0x7f112ba1c604 thread T0
2025-08-13T17:08:43.1373004Z     #0 0x7f1104fcbd2a in clang::driver::Compilation::~Compilation() (/github/home/ROOT-CI/build/lib/libCling.so+0x6ec6d2a) (BuildId: e78d3943a009ebe8d38b0867bfcbdc2db3cd9950)
2025-08-13T17:08:43.1374640Z     #1 0x7f110181925a in (anonymous namespace)::createCIImpl(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, cling::CompilerOptions const&, char const*, std::unique_ptr<clang::ASTConsumer, std::default_delete<clang::ASTConsumer> >, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&, bool, bool, bool) (/github/home/ROOT-CI/build/lib/libCling.so+0x371425a) (BuildId: e78d3943a009ebe8d38b0867bfcbdc2db3cd9950)
2025-08-13T17:08:43.1377085Z     #2 0x7f1101826d85 in cling::CIFactory::createCI(llvm::StringRef, cling::InvocationOptions const&, char const*, std::unique_ptr<clang::ASTConsumer, std::default_delete<clang::ASTConsumer> >, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&, bool) (/github/home/ROOT-CI/build/lib/libCling.so+0x3721d85) (BuildId: e78d3943a009ebe8d38b0867bfcbdc2db3cd9950)
2025-08-13T17:08:43.1378770Z     #3 0x7f1101dd319c in cling::IncrementalParser::IncrementalParser(cling::Interpreter*, char const*, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&) (/github/home/ROOT-CI/build/lib/libCling.so+0x3cce19c) (BuildId: e78d3943a009ebe8d38b0867bfcbdc2db3cd9950)
2025-08-13T17:08:43.1380504Z     #4 0x7f1101a3cff0 in cling::Interpreter::Interpreter(int, char const* const*, char const*, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&, void*, bool, cling::Interpreter const*) (/github/home/ROOT-CI/build/lib/libCling.so+0x3937ff0) (BuildId: e78d3943a009ebe8d38b0867bfcbdc2db3cd9950)
2025-08-13T17:08:43.1382114Z     #5 0x7f11012393aa in cling::Interpreter::Interpreter(int, char const* const*, char const*, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&, void*, bool) /github/home/ROOT-CI/src/interpreter/cling/include/cling/Interpreter/Interpreter.h:368
2025-08-13T17:08:43.1384049Z     #6 0x7f11015f3e56 in std::__detail::_MakeUniq<cling::Interpreter>::__single_object std::make_unique<cling::Interpreter, unsigned long, char const**, TString&, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > >&, void*&>(unsigned long&&, char const**&&, TString&, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > >&, void*&) /usr/include/c++/13/bits/unique_ptr.h:1070
2025-08-13T17:08:43.1385652Z     #7 0x7f110135bdba in TCling::TCling(char const*, char const*, char const* const*, void*) /github/home/ROOT-CI/src/core/metacling/src/TCling.cxx:1570
2025-08-13T17:08:43.1386278Z     #8 0x7f110134e5bb in CreateInterpreter /github/home/ROOT-CI/src/core/metacling/src/TCling.cxx:627
2025-08-13T17:08:43.1386809Z     #9 0x7f112e10aa60 in TROOT::InitInterpreter() /github/home/ROOT-CI/src/core/base/src/TROOT.cxx:2122
2025-08-13T17:08:43.1711565Z     #10 0x7f112e0f9c10 in ROOT::Internal::GetROOT2() /github/home/ROOT-CI/src/core/base/src/TROOT.cxx:391
2025-08-13T17:08:43.1781723Z     #11 0x7f112e0fa0c0 in ROOT::GetROOT() /github/home/ROOT-CI/src/core/base/src/TROOT.cxx:473
2025-08-13T17:08:43.1931629Z     #12 0x7f112dfed27c in TApplication::TApplication(char const*, int*, char**, void*, int) /github/home/ROOT-CI/src/core/base/src/TApplication.cxx:152
2025-08-13T17:08:43.2051591Z     #13 0x7f112e8bd52d in TRint::TRint(char const*, int*, char**, void*, int, bool, bool) /github/home/ROOT-CI/src/core/rint/src/TRint.cxx:174
2025-08-13T17:08:43.2132126Z     #14 0x563a4ccbea00 in main /github/home/ROOT-CI/src/main/src/rmain.cxx:81
2025-08-13T17:08:43.2291460Z     #15 0x7f112d6281c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 282c2c16e7b6600b0b22ea0c99010d2795752b5f)
2025-08-13T17:08:43.2292174Z     #16 0x7f112d62828a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 282c2c16e7b6600b0b22ea0c99010d2795752b5f)
2025-08-13T17:08:43.2292838Z     #17 0x563a4ccbe3c4 in _start (/github/home/ROOT-CI/build/bin/root.exe+0x33c4) (BuildId: 137b60cbcc7dbf343a3af3870d704a117d5e5ea0)
2025-08-13T17:08:43.2293206Z 
2025-08-13T17:08:43.2293505Z Address 0x7f112ba1c604 is located in stack of thread T0 at offset 1540 in frame
2025-08-13T17:08:43.2294125Z     #0 0x7f1119baeb1f in clang::ModuleMapParser::consumeToken() (/github/home/ROOT-CI/build/lib/libCling.so+0x1baa9b1f) (BuildId: e78d3943a009ebe8d38b0867bfcbdc2db3cd9950)
2025-08-13T17:08:43.2294600Z 
2025-08-13T17:08:43.2295160Z   This frame has 45 object(s):
2025-08-13T17:08:43.2295334Z     [48, 49) '<unknown>'
2025-08-13T17:08:43.2295491Z     [64, 68) 'Result' (line 1611)
2025-08-13T17:08:43.2295653Z     [80, 84) '<unknown>'
2025-08-13T17:08:43.2295795Z     [96, 100) 'X'
2025-08-13T17:08:43.2295925Z     [112, 116) 'X'
2025-08-13T17:08:43.2296190Z     [128, 132) 'X'
2025-08-13T17:08:43.2296318Z     [144, 148) 'X'
2025-08-13T17:08:43.2296436Z     [160, 164) 'X'
2025-08-13T17:08:43.2296570Z     [176, 184) 'Start' (line 1710)
2025-08-13T17:08:43.2296728Z     [208, 216) 'ULLVal'
2025-08-13T17:08:43.2296873Z     [240, 256) 'RI' (line 1620)
2025-08-13T17:08:43.2297110Z     [272, 288) '<unknown>'
2025-08-13T17:08:43.2297260Z     [304, 320) '<unknown>'
2025-08-13T17:08:43.2297470Z     [336, 352) '<unknown>'
2025-08-13T17:08:43.2297624Z     [368, 384) '<unknown>'
﻿2025-08-13T17:08:43.2301334Z     [400, 416) '<unknown>'
2025-08-13T17:08:43.2301504Z     [432, 448) '<unknown>'
2025-08-13T17:08:43.2301647Z     [464, 480) '<unknown>'
2025-08-13T17:08:43.2301856Z     [496, 512) '<unknown>'
2025-08-13T17:08:43.2302019Z     [528, 544) '<unknown>'
2025-08-13T17:08:43.2302166Z     [560, 576) '<unknown>'
2025-08-13T17:08:43.2302302Z     [592, 608) '<unknown>'
2025-08-13T17:08:43.2302516Z     [624, 640) '<unknown>'
2025-08-13T17:08:43.2302672Z     [656, 672) '<unknown>'
2025-08-13T17:08:43.2302832Z     [688, 704) '<unknown>'
2025-08-13T17:08:43.2302984Z     [720, 736) '<unknown>'
2025-08-13T17:08:43.2303142Z     [752, 768) '<unknown>'
2025-08-13T17:08:43.2303286Z     [784, 800) '<unknown>'
2025-08-13T17:08:43.2303538Z     [816, 832) '<unknown>'
2025-08-13T17:08:43.2303695Z     [848, 864) '<unknown>'
2025-08-13T17:08:43.2303917Z     [880, 896) 'NextIsIdent' (line 1734)
2025-08-13T17:08:43.2304114Z     [912, 928) '<unknown>'
2025-08-13T17:08:43.2304276Z     [944, 960) '<unknown>'
2025-08-13T17:08:43.2304460Z     [976, 992) '<unknown>'
2025-08-13T17:08:43.2304648Z     [1008, 1024) '<unknown>'
2025-08-13T17:08:43.2304846Z     [1040, 1056) '<unknown>'
2025-08-13T17:08:43.2305010Z     [1072, 1088) '<unknown>'
2025-08-13T17:08:43.2305340Z     [1104, 1128) 'LToken' (line 1615)
2025-08-13T17:08:43.2305528Z     [1168, 1192) '<unknown>'
2025-08-13T17:08:43.2305732Z     [1232, 1264) '<unknown>'
2025-08-13T17:08:43.2305896Z     [1296, 1328) '<unknown>'
2025-08-13T17:08:43.2306064Z     [1360, 1392) '<unknown>'
2025-08-13T17:08:43.2306261Z     [1424, 1480) 'SpellingBuffer' (line 1708)
2025-08-13T17:08:43.2306562Z     [1520, 2184) 'StringLiteral' (line 1689) <== Memory access at offset 1540 is inside this variable
2025-08-13T17:08:43.2306914Z     [2320, 3128) 'LangOpts' (line 1688)
2025-08-13T17:08:43.2307265Z HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
2025-08-13T17:08:43.2307667Z       (longjmp and C++ exceptions *are* supported)
2025-08-13T17:08:43.2308561Z SUMMARY: AddressSanitizer: stack-use-after-return (/github/home/ROOT-CI/build/lib/libCling.so+0x6ec6d2a) (BuildId: e78d3943a009ebe8d38b0867bfcbdc2db3cd9950) in clang::driver::Compilation::~Compilation()
2025-08-13T17:08:43.2309245Z Shadow bytes around the buggy address:
2025-08-13T17:08:43.2309497Z   0x7f112ba1c380: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2025-08-13T17:08:43.2309822Z   0x7f112ba1c400: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2025-08-13T17:08:43.2310136Z   0x7f112ba1c480: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2025-08-13T17:08:43.2310593Z   0x7f112ba1c500: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2025-08-13T17:08:43.2310919Z   0x7f112ba1c580: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2025-08-13T17:08:43.2311242Z =>0x7f112ba1c600:[f5]f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2025-08-13T17:08:43.2311551Z   0x7f112ba1c680: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2025-08-13T17:08:43.2311818Z   0x7f112ba1c700: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2025-08-13T17:08:43.2312123Z   0x7f112ba1c780: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2025-08-13T17:08:43.2312515Z   0x7f112ba1c800: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2025-08-13T17:08:43.2312828Z   0x7f112ba1c880: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2025-08-13T17:08:43.2313171Z Shadow byte legend (one shadow byte represents 8 application bytes):
2025-08-13T17:08:43.2313524Z   Addressable:           00
2025-08-13T17:08:43.2313802Z   Partially addressable: 01 02 03 04 05 06 07 
2025-08-13T17:08:43.2313999Z   Heap left redzone:       fa
2025-08-13T17:08:43.2314171Z   Freed heap region:       fd
2025-08-13T17:08:43.2314387Z   Stack left redzone:      f1
2025-08-13T17:08:43.2314546Z   Stack mid redzone:       f2
2025-08-13T17:08:43.2314756Z   Stack right redzone:     f3
2025-08-13T17:08:43.2314934Z   Stack after return:      f5
2025-08-13T17:08:43.2315140Z   Stack use after scope:   f8
2025-08-13T17:08:43.2315309Z   Global redzone:          f9
2025-08-13T17:08:43.2315506Z   Global init order:       f6
2025-08-13T17:08:43.2315834Z   Poisoned by user:        f7
2025-08-13T17:08:43.2316015Z   Container overflow:      fc
2025-08-13T17:08:43.2316217Z   Array cookie:            ac
2025-08-13T17:08:43.2316383Z   Intra object redzone:    bb
2025-08-13T17:08:43.2316583Z   ASan internal:           fe
2025-08-13T17:08:43.2316767Z   Left alloca redzone:     ca
2025-08-13T17:08:43.2316971Z   Right alloca redzone:    cb
```

@vgvassilev @hahnjo do you think it's a real diagnostic or a false positive that we should suppress?

We have in CIFactory.cpp:

`line 1277; clang::driver::Driver Drvr(ClangArgv[0], TheTriple.getTriple(), *Diags);`

so when it goes out of scope, the Driver::Compilation destructor seems to be accessing the StringLiteral via the ModuleOutputFile passed to several subfunctions:

`line 1689; llvm::SmallVector<char, 256> Output; llvm::sys::path::append(Output, COpts.CachePath, COpts.ModuleName + ".pcm"); StringRef ModuleOutputFile = StringRef(Output.data(), Output.size());`

**Comment by linev** [comment]
> > * roottest/root/io/references:  badly setup dependency on libEvent
> 
> [@linev](https://github.com/linev) did you address this point during your refactoring by chance?

I do not see dependency from `libEvent` in the `roottest/root/io/references` tests.

**Comment by ferdymercury** [comment]
> Also: when building on Ubu22 with asan, I get: See also: https://github.com/root-project/root/actions/runs/16941754812/job/48012438974?pr=19636
> 
> ```
> 2025-08-13T17:08:43.1371694Z ==90460==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f112ba1c604 at pc 0x7f1104fcbd2b bp 0x7ffc5d872180 sp 0x7ffc5d872170
> 2025-08-13T17:08:43.1372343Z READ of size 4 at 0x7f112ba1c604 thread T0
> 2025-08-13T17:08:43.1373004Z     #0 0x7f1104fcbd2a in clang::driver::Compilation::~Compilation() (/github/home/ROOT-CI/build/

Valgrind reports the same:

```
==374837== Invalid read of size 4
==374837==    at 0x7A39A38: clang::driver::Compilation::~Compilation() (in /home/user/build/build-root-Desktop-Debug/lib/libCling.so)
==374837==    by 0x6FEA6C7: (anonymous namespace)::createCIImpl(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, cling::CompilerOptions const&, char const*, std::unique_ptr<clang::ASTConsumer, std::default_delete<clang::ASTConsumer> >, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&, bool, bool, bool) (in /home/user/build/build-root-Desktop-Debug/lib/libCling.so)
==374837==    by 0x6FED5EF: cling::CIFactory::createCI(llvm::StringRef, cling::InvocationOptions const&, char const*, std::unique_ptr<clang::ASTConsumer, std::default_delete<clang::ASTConsumer> >, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&, bool) (in /home/user/build/build-root-Desktop-Debug/lib/libCling.so)
==374837==    by 0x70BF979: cling::IncrementalParser::IncrementalParser(cling::Interpreter*, char const*, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&) (in /home/user/build/build-root-Desktop-Debug/lib/libCling.so)
==374837==    by 0x7034A32: cling::Interpreter::Interpreter(int, char const* const*, char const*, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&, void*, bool, cling::Interpreter const*) (in /home/user/build/build-root-Desktop-Debug/lib/libCling.so)
==374837==    by 0x6D1461A: cling::Interpreter::Interpreter(int, char const* const*, char const*, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&, void*, bool) (Interpreter.h:368)
==374837==    by 0x6F3227A: std::_MakeUniq<cling::Interpreter>::__single_object std::make_unique<cling::Interpreter, unsigned long, char const**, TString&, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > >&, void*&>(unsigned long&&, char const**&&, TString&, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > >&, void*&) (unique_ptr.h:962)
==374837==    by 0x6DADFB6: TCling::TCling(char const*, char const*, char const* const*, void*) (TCling.cxx:1570)
==374837==    by 0x6DA7EC0: CreateInterpreter (TCling.cxx:627)
==374837==    by 0x4CBE89A: TROOT::InitInterpreter() (TROOT.cxx:2122)
==374837==    by 0x4CB7C59: ROOT::Internal::GetROOT2() (TROOT.cxx:391)
==374837==    by 0x4CB7FE3: ROOT::GetROOT() (TROOT.cxx:473)
==374837==  Address 0x1ffeffc3f4 is on thread 1's stack
==374837==  1164 bytes below stack pointer
```

**Comment by hahnjo** [comment]
> Valgrind reports the same:

This should be fixed with https://github.com/root-project/root/pull/19808. Note that this issue was originally about tests that were failing because of build system issue, I'm not sure it makes sense to discuss actual problems here...

**Comment by silverweed** [comment]
Just did a pass to check the status. I updated the OP with the results: all checked and striken-through tests seem to be working now (tested with GCC 16)
