### ISSUE TITLE
[master] root cppyy changes causing issues in dependent python projects

### ISSUE THREAD

**Issue by andresailer** [root-project/root#14904]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

This https://github.com/root-project/root/pull/14703 (my guess on the changes, I did not confirm that this is the case) seems to have caused issues in python projects depending on root.

E.g. https://lcgapp-services.cern.ch/cdash/testDetails.php?test=23867111&build=312289 
```
# setting LC_ALL to "C"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Thu/x86_64-el9-gcc11-opt/python/GaudiPython/__init__.py", line 29, in <module>
    from .Bindings import *  # noqa: F401 F403
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Thu/x86_64-el9-gcc11-opt/python/GaudiPython/Bindings.py", line 55, in <module>
    import cppyy
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Thu/x86_64-el9-gcc11-opt/lib/cppyy/__init__.py", line 71, in <module>
    from ._cpython_cppyy import *
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Thu/x86_64-el9-gcc11-opt/lib/cppyy/_cpython_cppyy.py", line 18, in <module>
    c = loader.load_cpp_backend()
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Thu/x86_64-el9-gcc11-opt/lib/cppyy_backend/loader.py", line 79, in load_cpp_backend
    raise RuntimeError("could not load cppyy_backend library")
RuntimeError: could not load cppyy_backend library
```

and many others in the list https://lcgapp-services.cern.ch/cdash/viewTest.php?onlyfailed&buildid=312289

Are we missing some required changes to build options?

### Reproducer

On any centos7 machine with cvmfs (or use available stack for your OS)
```
source /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/latest/x86_64-centos7-gcc11-dbg/setup.sh
python -c "import GaudiPython"
```

### ROOT version

Master from tonight.
Things were fine yesterday.

### Installation method

build from sources in lcgcmake, options https://gitlab.cern.ch/sft/lcgcmake/-/blob/master/projects/CMakeLists.txt#L95

### Operating system

centos7, alma9, alma8, ubuntu20, ubuntu22

**Comment by vepadulano** [comment]
Fix at https://gitlab.cern.ch/sft/lcgcmake/-/merge_requests/2141

**Comment by guitargeek** [comment]
@andresailer, can this issue be closed now?

**Comment by andresailer** [comment]
Give me few more hours, I don't yet have the tests reports for debug builds.

**Comment by andresailer** [comment]
Looks good now for me. Thanks @vepadulano @guitargeek

**Comment by vepadulano** [comment]
Tested on lxplus today, with `devswan`, `dev3` and `dev4`. All work correctly, so we can close this issue.

**Comment by guitargeek** [comment]
Fixed in "not applicabe" because the fix was in lcgmake
