### ISSUE TITLE
[TMVA] Python module compatibility problems

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#15309]
## Description

There are several known compatibility problems of PyMVA and SOFIE with common Python modules that need to be fixed:

### 1. Collisions of `openblas` because of SOFIE vs. NumPy
SOFIE can load an `openblas` version that is different from the one built in to NumPy, which can cause crashes for example on AlmaLinux 9 (the [TMVA_SOFIE_RSofieReader.C](https://github.com/root-project/root/blob/master/tutorials/CMakeLists.txt#L302) tutorial test is deactivated for this reason).

**Fixed by https://github.com/root-project/root/pull/18065**

### 2. TensorFlow 2.16 compatibility for Python 3.12 support
PyMVA doesn't work with TensorFlow>=2.16 because of the change from Keras 2 to Keras 3 in TensorFlow (that the motivation for this version check in [requirements.txt](https://github.com/root-project/root/blob/master/requirements.txt)). TensorFlow 2.16 support is important, because it's the first version that supports Python 3.12.

### 3. Collisions of `openblas` because of `tmva-cpu` vs NumPy
The TMVA CPU backend (activated with `tmva-cpu` has the same problem as stated in **1.**, because it also uses openblas. That's the reason why `tmva-cpu` is deactivated on `alma9`.

**Fixed by https://github.com/root-project/root/pull/18065**

### 4. Collisions of `std::regexp` because of cppyy vs {torch, xgboost}
Collisions of `std::regexp` that comes with cppyy with the `std::regexp` in XGBoost or PyTorch. This is more of a [cppyy issue](https://github.com/wlav/cppyy/issues/227) (or an issue of the other modules), but mostly affects PyMVA tutorials, because that's where ROOT is imported together with machine learning libraries. When this is fixed, 872886b and 1bf3d5a can be reverted.

Related issues:
  * https://github.com/root-project/root/issues/15211

**Comment by ellert** [comment]
The default blas version in RHEL/Alma/Rocky 9 is flexiblas. All system libraries linked to blas uses (or at least should use) it. This includes the numpy version provided by the system:

# rpm -q python3-numpy
python3-numpy-1.20.1-5.el9.x86_64
# rpm -q --requires python3-numpy | grep blas
libflexiblas.so.3()(64bit)

So if you are going to interact with system libraries that also use blas, you should use flexiblas.

Flexiblas is a wrapper library that make it possible the change the blas implementation used without recompiling by changing the configuration, the default configuration uses openblas.

As long as you link root against flexiblas you should be fine. The root package in EPEL 9 does this:

# rpm -q root-tmva
root-tmva-6.30.06-1.el9.x86_64
# rpm -q --requires root-tmva | grep blas
libflexiblas.so.3()(64bit)

CMake's FindBLAS module has higher priority for flexiblas than openblas, so you don't have to use any special flags to use it, as long as flexiblas-devel is installed.

**Comment by guitargeek** [comment]
Thanks, that's a very valuable insight! Indeed, on `alma9` it picked up flexiblas at the configuration:
https://github.com/root-project/root/actions/runs/8785067526/job/24104668181

```
  -- Found BLAS: /usr/lib64/libflexiblas.so  
```

The probably the symbol clash came from mixing flexiblas from the system with openblas from the numpy package

**Comment by ferdymercury** [comment]
BLAS related PR: https://github.com/root-project/root/pull/18065

**Comment by guitargeek** [comment]
Thanks for pointing that out! Problem number two would be fixed by #15790, but this is a bit unsafe to merge because we have TensorFlow 2.16. I think I will test this PR locally and then merge it when I see it works.

**Comment by guitargeek** [comment]
Similar issue:
  * https://github.com/wlav/cppyy/issues/227

**Comment by guitargeek** [comment]
The just-released PyTorch version 2.7 and also XGBoost>=2.1 have fixed these problems with the symbol clash!

There was a symbol redirection to `glibc_free`:
```txt
#7  0x00007ffff7ca947c in munmap_chunk (p=<optimized out>) at ./malloc/malloc.c:3040
#8  0x00007ffff7caddfa in __GI___libc_free (mem=0x7fffffffa2d8) at ./malloc/malloc.c:3388
#9  0x00007fffb50cd459 in std::__detail::_Compiler<std::regex_traits<char> >::_Compiler(char const*, char const*, std::locale const&, std::regex_constants::syntax_option_type) ()
   from /home/ajomy/ROOT/root_venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so
#10 0x00007fffb89f6577 in torch::jit::SourceImporterImpl::attributeAssignmentSpecialHandlingHack(c10::QualifiedName const&, torch::jit::Assign const&) () from /home/ajomy/ROOT/root_venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so
```

**Comment by guitargeek** [comment]
The only remaining compatibility problem at this point is the TensorFlow>=2.16 compatibility.

However, an executive decision on whether PyMVA should support the more recent TensorFlow versions is [still pending](https://github.com/root-project/root/pull/15790#issuecomment-2849345081). This is likely something that can't be decided in GitHub issue discussions, so I'm also closing my issue here at this point.
