### ISSUE TITLE
cppyy passing arguments by name to C++ binding

### ISSUE THREAD

**Issue by will-cern** [root-project/root#16406]
### Feature description

Is it possible to support passing arguments by name to a C++ method in cppyy, including passing out of order and not passing all arguments if some are defaulted? 

Here is an example:

```
import ROOT

ROOT.gInterpreter.ProcessLine("""
class MyClass {
public:
    class MyObj {
    public:
        MyObj(const char* in) : s(in) { }
        TString s;
    };
    void MyMethod(const MyObj& x="hello", bool opt=false, bool opt2=true) {
      std::cout << x.s << " " << opt << " " << opt2 << std::endl;
    }

};
""")

ROOT.MyClass().MyMethod(opt2=False,x="hi") # I'd like this to output "hi 0 0"
```
At the moment this produces:

```
File cppyy_default_compiler:1, in <module>

NameError: name 'false' is not defined
```

Thanks!

**Comment by guitargeek** [comment]
I thought this was already working :slightly_smiling_face: But okay, if it's not working I agree we should support this :+1: This will help a lot in making C++ interfaces feel more pythonic without writing explicit pythonization wrappers.

**Comment by dpiparo** [comment]
In master on macOS I even get
```
>>> ROOT.MyClass().MyMethod(opt2=False,x="hi") # I'd like this to output "hi 0 0"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cppyy_default_compiler", line 1, in <module>
NameError: name 'false' is not defined. Did you mean: 'False'?
```
:-)

**Comment by dpiparo** [comment]
Fixed in master, tested on macOS15 and lxplus.
```
lxplus901:~$ cat a.py 
import ROOT

ROOT.gInterpreter.ProcessLine("""
class MyClass {
public:
    class MyObj {
    public:
        MyObj(const char* in) : s(in) { }
        TString s;
    };
    void MyMethod(const MyObj& x="hello", bool opt=false, bool opt2=true) {
      std::cout << x.s << " " << opt << " " << opt2 << std::endl;
    }

};
""")

ROOT.MyClass().MyMethod(opt2=False,x="hi") # I'd like this to output "hi 0 0"

lxplus901:~$ python a.py 
hi 0 0
lxplus901:~$ which root
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-el9-gcc14-opt/bin/root
```

**Comment by guitargeek** [comment]
How cool is that!  Does it also work with 6.36? In any case I'd have a hard time identifying the right commit to backport here 🙂

**Comment by dpiparo** [comment]
This is really interesting. If you look at the test results, they are platform dependent (!). On some platforms, the reproducer works correctly, on others it does not. Curiously enough, I prepared it on a macOS 15 computer and double checked with LCG releases on alma9. On both it worked, but on ROOT's CI it failed on both!

**Comment by guitargeek** [comment]
It's a Python version issue. Your test in #19146 works only starting from Python 3.11 (compare also to [this page on Python version support windows](https://devguide.python.org/versions/)).

Here is the output on my system for Python 3.10 and 3.11:

```
Python 3.10.18 (main, Jun  3 2025, 18:23:41) [GCC 14.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>>
>>> ROOT.gInterpreter.ProcessLine("""
... class MyClass {
... public:
...     class MyObj {
...     public:
...         MyObj(const char* in) : s(in) { }
...         TString s;
...     };
...     void MyMethod(const MyObj& x="hello", bool opt=false, bool opt2=true) {
...       std::cout << x.s << " " << opt << " " << opt2 << std::endl;
...     }
... };
... """)
0
>>>
>>> ROOT.MyClass().MyMethod(opt2=False, x="hi")
hello 0 1
>>>
```

```
Python 3.11.13 (main, Jun  3 2025, 18:38:25) [GCC 14.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>>
>>> ROOT.gInterpreter.ProcessLine("""
... class MyClass {
... public:
...     class MyObj {
...     public:
...         MyObj(const char* in) : s(in) { }
...         TString s;
...     };
...     void MyMethod(const MyObj& x="hello", bool opt=false, bool opt2=true) {
...       std::cout << x.s << " " << opt << " " << opt2 << std::endl;
...     }
... };
... """)
0
>>>
>>> ROOT.MyClass().MyMethod(opt2=False, x="hi")
hi 0 0
>>>
```

We still have to support Python<=3.10 thought, because alma8 still comes with Python 3.8, which is the lowest Python version that we support.

Given I can easily compare ROOT builds with different Python versions on my machine, I will take a look at this issue an hopefully find a solution quickly. Because this situation where the results of a function depend of the Python version (where you silently get wrong results for Python<3.11) is not good.

**Comment by dpiparo** [comment]
@guitargeek this analysis is great. With calm, let's see what you find out and then we decide how to proceed. While Alma8 is still supported until the end of LS3, it's also true that only CMS uses it, however replacing the system python version with a recent one, as part of their externals. Moreover, lxplus has also fully transitioned to alma9, too.

**Comment by will-cern** [comment]
Getting this working has fantastic, will definitely start to play with it in our development branch (where we have ROOT master build)
