### ISSUE TITLE
TMVA/Sofie tutorials used same name for generated files bur are run in parallel.

### ISSUE THREAD

**Issue by pcanal** [root-project/root#16680]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

I see (for example in https://github.com/root-project/root/pull/16664/checks?check_run_id=31435842971): failures like:

```
/github/home/ROOT-CI/src/tutorials/tmva/TMVA_SOFIE_GNN_Application.C:10:10: fatal error: 'encoder.hxx' file not found
#include "encoder.hxx"
         ^~~~~~~~~~~~~
```
or 
```
Traceback (most recent call last):
  File "/home/pcanal/root_working/code/quick-devel/tutorials/tmva/TMVA_SOFIE_GNN.py", line 226, in <module>
    gnn = SofieGNN()
  File "/home/pcanal/root_working/code/quick-devel/tutorials/tmva/TMVA_SOFIE_GNN.py", line 150, in __init__
    self.encoder_session = ROOT.TMVA_SOFIE_encoder.Session()
TypeError: none of the 4 overloaded methods succeeded. Full details:
  Session::Session(TMVA_SOFIE_encoder::Session&&) =>
    TypeError: takes at least 1 arguments (0 given)
  Session::Session(const TMVA_SOFIE_encoder::Session&) =>
    TypeError: takes at least 1 arguments (0 given)
  Session::Session() =>
    runtime_error: TMVA-SOFIE failed to read the correct tensor name; expected name is tensor_EncodeProcessDecodeMLPGraphIndependentgraph_independentedge_modelmlplinear_3w0 , read 
0.00669210032
  void __cppyy_internal::init_TMVA_SOFIE_encoder__Session(TMVA_SOFIE_encoder::Session*& self, const TMVA_SOFIE_encoder::Edge_Update::Session& edge_update = TMVA_SOFIE_encoder::Edge
_Update::Session{}, const vector<float>& fEdgeInputs = vector<float>{}, const TMVA_SOFIE_encoder::Node_Update::Session& node_update = TMVA_SOFIE_encoder::Node_Update::Session{}, co
nst vector<float>& fNodeInputs = vector<float>{}, const TMVA_SOFIE_encoder::Global_Update::Session& global_update = TMVA_SOFIE_encoder::Global_Update::Session{}) =>
    runtime_error: TMVA-SOFIE failed to read the correct tensor name; expected name is tensor_EncodeProcessDecodeMLPGraphIndependentgraph_independentedge_modelmlplinear_3w0 , read 
0.00669210032
```

I also see from grepping:

```
./src/./tutorials/tmva/TMVA_SOFIE_GNN_Application.C
10:#include "encoder.hxx"

./src/./tutorials/tmva/TMVA_SOFIE_GNN.py
127:ROOT.gInterpreter.Declare('#include "encoder.hxx"')
```

So at least both of those test are uses the same generated file name (I can't find it in the repository) `encoder.hxx` and are still allowed to run in parallel ... leading to unstable result.

### Reproducer

Rerun  https://github.com/root-project/root/pull/16664/checks?check_run_id=31435842971

### ROOT version

master

### Installation method

both local install and CI

### Operating system

linux

**Comment by pcanal** [comment]
Thanks.
