### ISSUE TITLE
another crash in finalization 

### ISSUE THREAD

**Issue by VanyaBelyaev** [root-project/root#16942]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

I am using ROOT from LCG dev3 nightly build.
And  I see following crash in finalization:
```
The lines below might hint at the cause of the crash. If you see question
marks as part of the stack trace, try to recompile with debugging information
enabled and export CLING_DEBUG=1 environment variable before running.
You may get help by asking at the ROOT forum https://root.cern/forum
preferably using the command (.forum bug) in the ROOT prompt.
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern/bugs or (preferably) using the command (.gh bug) in
the ROOT prompt. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x0000000004f5e190 in ?? ()
#7  0x00007f8717736625 in CPyCppyy::op_dealloc_nofree(CPyCppyy::CPPInstance*) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Wed/x86_64-el9-gcc14-opt/lib/libcppyy.so
#8  0x00007f8717736661 in CPyCppyy::op_dealloc(CPyCppyy::CPPInstance*) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Wed/x86_64-el9-gcc14-opt/lib/libcppyy.so
#9  0x00007f8738dbcc9a in subtype_dealloc (self=0x7f873688d310) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Objects/typeobject.c:1463
#10 0x00007f8738d78faa in Py_DECREF (op=<optimized out>) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Include/object.h:538
#11 Py_XDECREF (op=<optimized out>) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Include/object.h:602
#12 list_dealloc (op=0x7f87171b02c0) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Objects/listobject.c:357
#13 0x00007f8738d9750c in _PyDict_DelItem_KnownHash (op=0x7f87387d6840, key=0x7f8738247e70, hash=7661047226539082438) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Objects/dictobject.c:2028
#14 0x00007f8738e53480 in _PyEval_EvalFrameDefault (tstate=0x7f8739186678 <_PyRuntime+166328>, frame=0x7f87393610a8, throwflag=0) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Python/ceval.c:2376
#15 0x00007f8738e59f30 in _PyEval_EvalFrame (tstate=0x7f8739186678 <_PyRuntime+166328>, frame=0x7f8739361020, throwflag=0) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Include/internal/pycore_ceval.h:73
#16 _PyEval_Vector (tstate=0x7f8739186678 <_PyRuntime+166328>, func=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Python/ceval.c:6434
#17 0x00007f8738d53a43 in _PyObject_VectorcallTstate (tstate=0x7f8739186678 <_PyRuntime+166328>, callable=0x7f8737501da0, args=0x7fff80da7eb8, nargsf=1, kwnames=0x0) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Include/internal/pycore_call.h:92
#18 method_vectorcall (method=<optimized out>, args=0x7f873916c2f0 <_PyRuntime+58928>, nargsf=<optimized out>, kwnames=0x0) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Objects/classobject.c:67
#19 0x00007f8738ec7bbf in atexit_callfuncs (state=0x7f873916d0c8 <_PyRuntime+62472>) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Modules/atexitmodule.c:98
#20 0x00007f8738ec7f3c in _PyAtExit_Call (interp=<optimized out>) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Modules/atexitmodule.c:118
#21 0x00007f8738e9d4b1 in Py_FinalizeEx () at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Python/pylifecycle.c:1779
#22 Py_FinalizeEx () at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Python/pylifecycle.c:1751
#23 0x00007f8738ec3f77 in Py_RunMain () at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Modules/main.c:682
#24 0x00007f8738ec4be3 in pymain_main (args=0x7fff80da80b0) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Modules/main.c:710
#25 Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at /build/jenkins/workspace/lcg_nightly_pipeline/build/externals/Python-3.11.9/src/Python/3.11.9/Modules/main.c:734
#26 0x00007f8738829590 in __libc_start_call_main () from /lib64/libc.so.6
#27 0x00007f8738829640 in __libc_start_main_impl () from /lib64/libc.so.6
#28 0x0000000000401075 in _start ()
===========================================================

```

### Reproducer

Reproducer is very simple, lets cal this file `tst_102.py`

```
import ROOT

objects = [
    ROOT.TF1      (  'f1'  , 'sin(x)/x' ) , 
    ROOT.TF2      (  'f2'  , 'sin(x)*sin(y)/x/y') ,    
]

rfile = ROOT.TFile ( 'ququ.root' , 'RECREATE' )
rfile.cd()
for o in objects :
    o.Write() 
rfile.ls()
rfile.Close()
```

1) It works OK  (last Friday nightlies)

```
 ( rm ququ.root ; CMTCONFIG=x86_64-el9-gcc14-opt ; source /cvmfs/sft.cern.ch/lcg/views/dev3/Fri/$CMTCONFIG/setup.sh ; ipython ./tst_102.py ) 
```

2) this one crashes: 

```
( rm -f ququ.root ; CMTCONFIG=x86_64-el9-gcc14-opt ; source /cvmfs/sft.cern.ch/lcg/views/dev3/Thu/$CMTCONFIG/setup.sh ; ipython ./tst_102.py )
```

### ROOT version

ROOT from LCG dev3 nightlies 

### Installation method

LCG nightly builts at cvmfs 

### Operating system

Linux

**Comment by vepadulano** [comment]
Thank you @VanyaBelyaev for the report! See the linked PR for a fix
