### ISSUE TITLE
Segmentation violation in TPaveLabel class

### ISSUE THREAD

**Issue by andriish** [root-project/root#6375]
## Describe the bug
Crash.
```
[user@lxplus733 ~]$ g++ pavelabel.cxx $(root-config --glibs --cflags --libs) -o pavelabel  -g
[user@lxplus733 ~]$ ./pavelabel 
Warning in <UnknownClass::SetDisplay>: DISPLAY not set, setting it to hostname:0.0

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
    gdb.printing.register_pretty_printer(gdb.current_objfile(),
    gdb.printing.register_pretty_printer(gdb.current_objfile(),
#0  0x00007f4b1f57246c in waitpid () from /lib64/libc.so.6
#1  0x00007f4b1f4eff62 in do_system () from /lib64/libc.so.6
#2  0x00007f4b23f015dc in TUnixSystem::StackTrace() () from /usr/lib64/root/libCore.so.6.22
#3  0x00007f4b23f0406a in TUnixSystem::DispatchSignals(ESignals) () from /usr/lib64/root/libCore.so.6.22
#4  <signal handler called>
#5  0x00007f4b22407674 in TPad::PaintBox(double, double, double, double, char const*) () from /usr/lib64/root/libGpad.so.6.22
#6  0x00007f4b229661a3 in TBox::PaintBox(double, double, double, double, char const*) () from /usr/lib64/root/libGraf.so.6.22
#7  0x00007f4b229a7570 in TPave::PaintPave(double, double, double, double, int, char const*) () from /usr/lib64/root/libGraf.so.6.22
#8  0x00007f4b229aa009 in TPaveLabel::PaintPaveLabel(double, double, double, double, char const*, char const*) () from /usr/lib64/root/libGraf.so.6.22
#9  0x0000000000400d05 in main (argc=1, argv=0x7fff9bced0c8) at pavelabel.cxx:13
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007f4b22407674 in TPad::PaintBox(double, double, double, double, char const*) () from /usr/lib64/root/libGpad.so.6.22
#6  0x00007f4b229661a3 in TBox::PaintBox(double, double, double, double, char const*) () from /usr/lib64/root/libGraf.so.6.22
#7  0x00007f4b229a7570 in TPave::PaintPave(double, double, double, double, int, char const*) () from /usr/lib64/root/libGraf.so.6.22
#8  0x00007f4b229aa009 in TPaveLabel::PaintPaveLabel(double, double, double, double, char const*, char const*) () from /usr/lib64/root/libGraf.so.6.22
#9  0x0000000000400d05 in main (argc=1, argv=0x7fff9bced0c8) at pavelabel.cxx:13
===========================================================


[user@lxplus733 ~]$ 
```

## Expected behavior
No segmentation violation.

## To Reproduce
Code:
```
#include <TCanvas.h>
#include <TPaveLabel.h>
#include <TPad.h>
#include <fenv.h>

int main(int argc, char **argv) {
    feenableexcept(FE_DIVBYZERO | FE_INVALID | FE_OVERFLOW);
    TCanvas* C= new TCanvas("canvas","canvas",2000,10);
    C->cd();
    TPad* p= new TPad();
    p->cd();
    TPaveLabel* l= new TPaveLabel(0,1,0,1,"I hope not crash");
    l->Paint();//Crash here
    return 0;
}
```
Compile

```
g++ pavelabel.cxx $(root-config --glibs --cflags --libs) -o pavelabel  -g
```
Run 
```
./pavelabel
```

## Setup
ROOT 6.22.02 as installed on lxplus.

## Additional context
This is a piece of #6344  (hopefully the last one)

**Comment by couet** [comment]
This one give a crash on Ubuntu:
```
$ g++ pavelabel.cxx $(root-config --glibs --cflags --libs) -o pavelabel  -g
$ ./pavelabel

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f0abbc31c2a in __GI___wait4 (pid=1802850, stat_loc=stat_loc
entry=0x7ffd75e11aa8, options=options
entry=0, usage=usage
entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00007f0abbc31beb in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc
entry=0x7ffd75e11aa8, options=options
entry=0) at waitpid.c:38
#2  0x00007f0abbba10e7 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:172
#3  0x00007f0abc5fc82e in TUnixSystem::StackTrace() () from /home/sftnight/couet/build/lib/libCore.so
#4  0x00007f0abc5f96b5 in TUnixSystem::DispatchSignals(ESignals) () from /home/sftnight/couet/build/lib/libCore.so
#5  <signal handler called>
#6  0x00007f0abc0edb04 in TPad::PaintBox(double, double, double, double, char const*) [clone .cold] () from /home/sftnight/couet/build/lib/libGpad.so
#7  0x00007f0abc203909 in TBox::PaintBox(double, double, double, double, char const*) () from /home/sftnight/couet/build/lib/libGraf.so
#8  0x00007f0abc24db3d in TPave::PaintPave(double, double, double, double, int, char const*) () from /home/sftnight/couet/build/lib/libGraf.so
#9  0x00007f0abc2517ad in TPaveLabel::PaintPaveLabel(double, double, double, double, char const*, char const*) () from /home/sftnight/couet/build/lib/libGraf.so
#10 0x00005635d042e337 in main (argc=1, argv=0x7ffd75e14b58) at pavelabel.cxx:13
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007f0abc0edb04 in TPad::PaintBox(double, double, double, double, char const*) [clone .cold] () from /home/sftnight/couet/build/lib/libGpad.so
#7  0x00007f0abc203909 in TBox::PaintBox(double, double, double, double, char const*) () from /home/sftnight/couet/build/lib/libGraf.so
#8  0x00007f0abc24db3d in TPave::PaintPave(double, double, double, double, int, char const*) () from /home/sftnight/couet/build/lib/libGraf.so
#9  0x00007f0abc2517ad in TPaveLabel::PaintPaveLabel(double, double, double, double, char const*, char const*) () from /home/sftnight/couet/build/lib/libGraf.so
#10 0x00005635d042e337 in main (argc=1, argv=0x7ffd75e14b58) at pavelabel.cxx:13
===========================================================

```

**Comment by couet** [comment]
Even a valid PaveLabel crashes when Paint is called directly.
```
root [0] TPaveLabel* l= new TPaveLabel(0,0,1,1,"I hope not crash");
root [1] l->Paint()

 *** Break *** segmentation violation

```

**Comment by couet** [comment]
now fixed
