### ISSUE TITLE
Potential null pointer dereference in TPad::Close

### ISSUE THREAD

**Issue by andriish** [root-project/root#6453]
## Describe the bug
Crash
```

[@lxplus795 test]$ ./pad6.exe 
Warning in <UnknownClass::SetDisplay>: DISPLAY not set, setting it to 

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fc0d7d5e46c in waitpid () from /lib64/libc.so.6
#1  0x00007fc0d7cdbf62 in do_system () from /lib64/libc.so.6
#2  0x00007fc0d99070bc in TUnixSystem::StackTrace() () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python3/Fri/x86_64-centos7-gcc10-opt/lib/libCore.so
#3  0x00007fc0d99046d5 in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python3/Fri/x86_64-centos7-gcc10-opt/lib/libCore.so
#4  <signal handler called>
#5  0x00007fc0d9056288 in TPad::Close(char const*) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python3/Fri/x86_64-centos7-gcc10-opt/lib/libGpad.so
#6  0x00007fc0d905f746 in TPad::~TPad() [clone .part.0] () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python3/Fri/x86_64-centos7-gcc10-opt/lib/libGpad.so
#7  0x00007fc0d905f919 in TPad::~TPad() () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python3/Fri/x86_64-centos7-gcc10-opt/lib/libGpad.so
#8  0x000000000040124b in main (argc=<optimized out>, argv=<optimized out>) at test/pad6.cxx:9
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007fc0d9056288 in TPad::Close(char const*) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python3/Fri/x86_64-centos7-gcc10-opt/lib/libGpad.so
#6  0x00007fc0d905f746 in TPad::~TPad() [clone .part.0] () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python3/Fri/x86_64-centos7-gcc10-opt/lib/libGpad.so
#7  0x00007fc0d905f919 in TPad::~TPad() () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python3/Fri/x86_64-centos7-gcc10-opt/lib/libGpad.so
#8  0x000000000040124b in main (argc=<optimized out>, argv=<optimized out>) at /test/pad6.cxx:9
===========================================================

```

## Expected behavior
No crash.

## To Reproduce
Code 
```
#include <TCanvas.h>

int main(int argc, char **argv) {
    TCanvas* C= new TCanvas("cnvas","canvas",1024,768);
    C->cd();
    TPad* c= new TPad();
    c->SetPad(0,0,1,1);
    c->cd(1);
    delete c;
    delete C;
    return 0;
}

```
Compile
```
g++ pad6.cxx $(root-config --glibs --cflags --libs) -o pad6 -g
```

Run
```
./pad6
```

## Setup
EPEL ROOT 62202/gcc485/CentOS7
ROOT night buil/gcc10/lxplus
 
## Additional context
Possible fix in Tpad::Close
Replace
```
      if (fCanvas->GetPadSave() == this)
         fCanvas->ClearPadSave();
      if (fCanvas->GetSelectedPad() == this)
         fCanvas->SetSelectedPad(0);
      if (fCanvas->GetClickSelectedPad() == this)
         fCanvas->SetClickSelectedPad(0);
```
with

```
if (fCanvas)
{
      if (fCanvas->GetPadSave() == this)
         fCanvas->ClearPadSave();
      if (fCanvas->GetSelectedPad() == this)
         fCanvas->SetSelectedPad(0);
      if (fCanvas->GetClickSelectedPad() == this)
         fCanvas->SetClickSelectedPad(0);
}
```

**Comment by couet** [comment]
PR here https://github.com/root-project/root/pull/6463

**Comment by couet** [comment]
./pad6 does not crash anymore
