### ISSUE TITLE
pytest shipped in roottest is not compatible with py3.9

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#6597]
```
The following tests FAILED:
        1312 - roottest-python-basic-basic (Failed)
        1313 - roottest-python-basic-datatype (Failed)
        1315 - roottest-python-basic-overload (Failed)
        1409 - roottest-python-pythonizations-pythonizations (Failed)
        1410 - roottest-python-pythonizations-smartptr (Failed)
        1413 - roottest-python-stl-stl (Failed)
        2106 - roottest-root-tree-fastcloning-runabstract-copy (Failed)
```

All tests have the following issue:

```
    Start 1312: roottest-python-basic-basic

1312: Test command: /usr/bin/cmake "-DCMD=/usr/bin/timeout^-s^USR2^270s^/home/sftnight/swunsch/python/bin/python3^/home/sftnight/swunsch/root/roottest/python/basic/PyROOT_basictests.py^--fixcling" "-DPRE=/home/sftnight/swunsch/build/bin/root.exe^-b^-q^-l^-e^.L ArgumentPassingCompiled.C+" "-DOUT=/home/sftnight/swunsch/build/roottest/python/basic/basic.log" "-DCWD=/home/sftnight/swunsch/build/roottest/python/basic" "-DDIFFCMD=/home/sftnight/swunsch/python/bin/python3^/home/sftnight/swunsch/root/roottest/scripts/custom_diff.py" "-DCHECKOUT=true" "-DCHECKERR=true" "-DSYS=/home/sftnight/swunsch/build" "-DENV=LEGACY_PYROOT=False#ROOTSYS=/home/sftnight/swunsch/build#PATH=/home/sftnight/swunsch/build/bin:/home/sftnight/swunsch/python/bin:/home/sftnight/.local/bin:/home/sftnight/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin#PYTHONPATH=/home/sftnight/swunsch/build/lib:#LD_LIBRARY_PATH=/home/sftnight/swunsch/build/lib:/home/sftnight/swunsch/python/lib:" "-DCOPY=/home/sftnight/swunsch/root/roottest/python/basic/ArgumentPassingCompiled.C^/home/sftnight/swunsch/root/roottest/python/basic/ReturnValues.C^/home/sftnight/swunsch/root/roottest/python/basic/SimpleClass.C^/home/sftnight/swunsch/root/roottest/python/basic/ArgumentPassingInterpreted.C" "-P" "/home/sftnight/swunsch/build/RootTestDriver.cmake"
1312: Environment variables: 
1312:  ROOT_HIST=0
1312: Test timeout computed to be: 300
1312: Info in <TUnixSystem::ACLiC>: creating shared library /home/sftnight/swunsch/build/roottest/python/basic/./ArgumentPassingCompiled_C.so
1312: 
1312: -- TEST COMMAND -- 
1312: cd /home/sftnight/swunsch/build/roottest/python/basic
1312: /usr/bin/timeout -s USR2 270s /home/sftnight/swunsch/python/bin/python3 /home/sftnight/swunsch/root/roottest/python/basic/PyROOT_basictests.py --fixcling
1312: -- BEGIN TEST OUTPUT --
1312: INTERNALERROR> Traceback (most recent call last):
1312: INTERNALERROR>   File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/main.py", line 77, in wrap_session
1312: INTERNALERROR>     config.do_configure()
1312: INTERNALERROR>   File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/config.py", line 608, in do_configure
1312: INTERNALERROR>     self.hook.pytest_configure(config=self)
1312: INTERNALERROR>   File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/core.py", line 377, in __call__
1312: INTERNALERROR>     return self._docall(methods, kwargs)
1312: INTERNALERROR>   File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/core.py", line 388, in _docall
1312: INTERNALERROR>     res = mc.execute()
1312: INTERNALERROR>   File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/core.py", line 289, in execute
1312: INTERNALERROR>     res = method(**kwargs)
1312: INTERNALERROR>   File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/assertion/__init__.py", line 56, in pytest_configure
1312: INTERNALERROR>     warn_about_missing_assertion(mode)
1312: INTERNALERROR>   File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/assertion/__init__.py", line 113, in warn_about_missing_assertion
1312: INTERNALERROR>     assert False
1312: INTERNALERROR> AssertionError
1312: ! /home/sftnight/swunsch/root/roottest/python/pytest/_pytest/assertion/__init__.py
1312:  Traceback (most recent call last):
1312:    File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/main.py", line 77, in wrap_session
1312:      config.do_configure()
1312:    File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/config.py", line 608, in do_configure
1312:      self.hook.pytest_configure(config=self)
1312:    File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/core.py", line 377, in __call__
1312:      return self._docall(methods, kwargs)
1312:    File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/core.py", line 388, in _docall
1312:      res = mc.execute()
1312:    File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/core.py", line 289, in execute
1312:      res = method(**kwargs)
1312:    File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/assertion/__init__.py", line 56, in pytest_configure
1312:      warn_about_missing_assertion(mode)
1312:    File "/home/sftnight/swunsch/root/roottest/python/pytest/_pytest/assertion/__init__.py", line 113, in warn_about_missing_assertion
1312:      assert False
1312:  AssertionError
1312: 
1312: -- END TEST OUTPUT --
1312: CMake Error at /home/sftnight/swunsch/build/RootTestDriver.cmake:191 (message):
1312:   got exit code 3 but expected 0
1312: 
1312: 
1/1 Test #1312: roottest-python-basic-basic ......***Failed    5.07 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   6.17 sec

The following tests FAILED:
        1312 - roottest-python-basic-basic (Failed)

```

That means our pytest in roottest is not compatible with py3.9. We can either hotfix our own pytest distribution or remove the inbuilt module and use official versions.

**Comment by stwunsch** [comment]
A possible fix is https://github.com/root-project/roottest/pull/610, which simply removes the inbuilt pytest and requires an external version.
