### ISSUE TITLE
[TTreeReader] Segfault when reading branch of "automatically loaded" friend

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#6993]
- [x] Checked for duplicates

### Describe the bug

A seemingly valid usage of TTreeReader with friends causes a segfault because of the dereference of a null `directorTree`:

```c++
#8  0x00007f58ac8f3cac in GetFriendBranchName (directorTree=0x0, branch=0x561d8a909570, fullBranchName=0x561d8a909589 "x") at ../../../root_dbg/tree/treeplayer/src/TBranchProxy.cxx:116
#9  0x00007f58ac8f3fe8 in ROOT::Detail::TBranchProxy::TBranchProxy (this=0x561d8a901cf0, boss=0x561d88ead730, branchname=0x561d8a909589 "x", branch=0x561d8a909570, membername=0x7ffdab5e1a89 "") at ../../../root_dbg/tree/treeplayer/src/TBranchProxy.cxx:133
#10 0x00007f58ac999032 in ROOT::Internal::TNamedBranchProxy::TNamedBranchProxy (this=0x561d8a901cf0, boss=0x561d88ead730, branch=0x561d8a909570, fullname=0x7ffdab5e1ae0 "t2.x", proxyname=0x561d8a909589 "x", membername=0x7ffdab5e1a89 "") at ../../../root_dbg/tree/treeplayer/inc/TTreeReaderUtils.h:52
#11 0x00007f58ac997941 in ROOT::Internal::TTreeReaderValueBase::CreateProxy (this=0x7ffdab5e1da0) at ../../../root_dbg/tree/treeplayer/src/TTreeReaderValue.cxx:644
#12 0x00007f58ac988287 in TTreeReader::SetProxies (this=0x7ffdab5e2070) at ../../../root_dbg/tree/treeplayer/src/TTreeReader.cxx:356
#13 0x00007f58ac98901b in TTreeReader::SetEntryBase (this=0x7ffdab5e2070, entry=0, local=false) at ../../../root_dbg/tree/treeplayer/src/TTreeReader.cxx:609
#14 0x0000561d87cc8858 in TTreeReader::SetEntry (this=0x7ffdab5e2070, entry=0) at /home/eguiraud/ROOT/build_dbg/include/TTreeReader.h:191
#15 0x0000561d87cc8829 in TTreeReader::Next (this=0x7ffdab5e2070) at /home/eguiraud/ROOT/build_dbg/include/TTreeReader.h:183
#16 0x0000561d87cc863b in main () at repro_treereader.cpp:42
```

### To Reproduce

```c++
#include <TChain.h>
#include <TTreeReader.h>
#include <TTreeReaderValue.h>
#include <TTree.h>
#include <TFile.h>
#include <ROOT/RDataFrame.hxx>
#include <iostream>

int main()
{
   {
      // write a TTree and its friend to the same file:
      // when t1 is read back, it automatically also loads its friend
      TFile f("f.root", "recreate");
      TTree t1("t1", "t1");
      TTree t2("t2", "t2");
      int x = 42;
      t2.Branch("x", &x);
      t1.Fill();
      t2.Fill();
      t1.AddFriend(&t2);
      t1.Write();
      t2.Write();
      f.Close();
   }

   {
      // reading t2.x via chain->SetBranchAddress works
      TChain c;
      c.Add("f.root/t1");
      c.LoadTree(0);
      int x = 0;
      c.SetBranchAddress("t2.x", &x);
      c.GetEntry(0);
      std::cout << x << '\n'; // prints 42
   }

   {
      // reading t2.x via TTreeReader segfaults
      TChain c;
      c.Add("f.root/t1");
      c.LoadTree(0);
      TTreeReader r(&c);
      TTreeReaderValue<int> rv(r, "t2.x");
      r.Next();
   }

   return 0;
}
```

### Setup

ROOT master@b694869108 (v6.23).

### Additional context

This blocks #6741 .

Using TTree directly instead of passing through TChain works:

```c++
   {                                                                                                                                                                                     
      TFile f("f.root");                                                                                                
      auto *t = f.Get<TTree>("t1");                                                                                     
      TTreeReader r(t);                                                                                                 
      TTreeReaderValue<int> rv(r, "t2.x");                                                                              
      r.Next();
      std::cout << *rv << std::endl; // prints 42                                                                                                         
   }  
```

**Comment by eguiraud** [comment]
WIP at https://github.com/root-project/root/pull/6995
