### ISSUE TITLE
Segmentation fault after quitting Cling in CUDA mode

### ISSUE THREAD

**Issue by SimeonEhrig** [root-project/root#7433]
### Describe the bug
After the commit 2c4a756d38d9b5f0348f645a116b3014159f03d6, I get a segmentation fault in Cling when I use the CUDA mode, define a kernel and exit Cling.

```
$ ./cling --std=c++14 -xcuda --cuda-path=/opt/spack-modules/linux-ubuntu20.04-skylake_avx512/gcc-10.2.0/cuda-10.1.243-7i5cvq4bobfu6g23zltag3fpcwdlc3ye --cuda-gpu-arch=sm_35

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ __global__ void g(){}
[cling]$ .q
Segmentation fault (core dumped)
```

The stack trace in gdb is:

```
***************** CLING *****************
Type C++ code and press enter to run it
Type .q to exit
*******************************************
[cling]$ _global_ void g(){}
[cling]$ .q

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ffb1a0 in ?? ()
(gdb) bt
#0 0x00007ffff7ffb1a0 in ?? ()
#1 0x00007ffff65e6a27 in __run_exit_handlers (status=0, listp=0x7ffff6788718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true,
run_dtors=run_dtors@entry=true) at exit.c:108
#2 0x00007ffff65e6be0 in __GI_exit (status=<optimized out>) at exit.c:139
#3 0x00007ffff65c40ba in __libc_start_main (main=0x1058ad0 <main(int, char**)>, argc=5, argv=0x7fffffff4448, init=<optimized out>, fini=<optimized out>,
rtld_fini=<optimized out>, stack_end=0x7fffffff4438) at ../csu/libc-start.c:342
#4 0x0000000000c5aa6e in _start ()
(gdb) where
#0 0x00007ffff7ffb1a0 in ?? ()
#1 0x00007ffff65e6a27 in __run_exit_handlers (status=0, listp=0x7ffff6788718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true,
run_dtors=run_dtors@entry=true) at exit.c:108
#2 0x00007ffff65e6be0 in __GI_exit (status=<optimized out>) at exit.c:139
#3 0x00007ffff65c40ba in __libc_start_main (main=0x1058ad0 <main(int, char**)>, argc=5, argv=0x7fffffff4448, init=<optimized out>, fini=<optimized out>,
rtld_fini=<optimized out>, stack_end=0x7fffffff4438) at ../csu/libc-start.c:342
#4 0x00
```
The `CodeUnloading/AtExit.C` cling test also fails with the commit.

### Setup

1. ROOT master beginning from commit 2c4a756d38d9b5f0348f645a116b3014159f03d6
2. Operating system: Ubuntu 20.04.2

**Comment by Harshalzzzzzzz** [comment]
@SimeonEhrig  @vgvassilev 
Dear Mentor,
I'm interested in contributing to the Root project and I would like to work on this issue. Can you please elaborate more on what needs to be done, since I'm a new to the project?
Thanks!

**Comment by Axel-Naumann** [comment]
This might be fixed in master since about 2 minutes - https://github.com/root-project/root/pull/7506

**Comment by SimeonEhrig** [comment]
@Axel-Naumann I tested your fix with my CUDA system. The segmentation error is gone and all tests passes. Thanks for fixing it.
