### ISSUE TITLE
 *** Break *** segmentation violation

### ISSUE THREAD

**Issue by meena382** [root-project/root#7496]
```
Thread 6 (Thread 0x7f932f93e700 (LWP 8838)):
#0  0x00007f9369773d19 in syscall () from /lib64/libc.so.6
#1  0x00007f9331a0e79e in XrdSys::LinuxSemaphore::Wait (this=0x7ee4870) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7ee4698) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7ee4680) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f9331a0e989 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/XrdCl/XrdClJobManager.cc:33
#5  0x00007f9369a50ea5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f93697799fd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7f933013f700 (LWP 8837)):
#0  0x00007f9369773d19 in syscall () from /lib64/libc.so.6
#1  0x00007f9331a0e79e in XrdSys::LinuxSemaphore::Wait (this=0x7ee4870) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7ee4698) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7ee4680) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f9331a0e989 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/XrdCl/XrdClJobManager.cc:33
#5  0x00007f9369a50ea5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f93697799fd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7f9330940700 (LWP 8836)):
#0  0x00007f9369773d19 in syscall () from /lib64/libc.so.6
#1  0x00007f9331a0e79e in XrdSys::LinuxSemaphore::Wait (this=0x7ee4870) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7ee4698) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7ee4680) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f9331a0e989 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/XrdCl/XrdClJobManager.cc:33
#5  0x00007f9369a50ea5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f93697799fd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7f9331141700 (LWP 8835)):
#0  0x00007f9369a57e9d in nanosleep () from /lib64/libpthread.so.0
#1  0x00007f9331b1dded in XrdSysTimer::Wait (mills=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/XrdSys/XrdSysTimer.cc:239
#2  0x00007f93319b2118 in XrdCl::TaskManager::RunTasks (this=0x7ee9660) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/XrdCl/XrdClTaskManager.cc:244
#3  0x00007f93319b2269 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/XrdCl/XrdClTaskManager.cc:37
#4  0x00007f9369a50ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f93697799fd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f9331942700 (LWP 8834)):
#0  0x00007f9369779fd3 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f9331b22c17 in XrdSys::IOEvents::PollE::Begin (this=0x7efc120, syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/./XrdSys/XrdSysIOEventsPollE.icc:213
#2  0x00007f9331b1f4f5 in XrdSys::IOEvents::BootStrap::Start (parg=0x7ffe2f5220d0) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/XrdSys/XrdSysIOEvents.cc:131
#3  0x00007f9331b1d5e8 in XrdSysThread_Xeq (myargs=0x7edce20) at /build/cmsbld/auto-builds/CMSSW_10_2_0_pre6-slc7_amd64_gcc700/build/CMSSW_10_2_0_pre6-build/BUILD/slc7_amd64_gcc700/external/xrootd/4.8.3-gnimlf/xrootd-4.8.3/src/XrdSys/XrdSysPthread.cc:86
#4  0x00007f9369a50ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f93697799fd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f93693e3980 (LWP 5985)):
#0  0x00007f9369740549 in waitpid () from /lib64/libc.so.6
#1  0x00007f93696bdfb2 in do_system () from /lib64/libc.so.6
#2  0x00007f93696be361 in system () from /lib64/libc.so.6
#3  0x00007f936a27fa8b in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCore.so
#4  0x00007f936a2820cc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCore.so
#5  <signal handler called>
#6  0x00007f93685d3a6b in int TStreamerInfoActions::VectorLooper::ReadCollectionBasicType<float>(TBuffer&, void*, TStreamerInfoActions::TConfiguration const*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libRIO.so
#7  0x00007f93684dd684 in TBufferFile::ApplySequence(TStreamerInfoActions::TActionSequence const&, void*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libRIO.so
#8  0x00007f935cc63f51 in TBranchElement::ReadLeavesMember(TBuffer&) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libTree.so
#9  0x00007f935cc56bd4 in TBranch::GetEntry(long long, int) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libTree.so
#10 0x00007f935cc6f4f9 in TBranchElement::GetEntry(long long, int) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libTree.so
#11 0x00007f935ccb5801 in TTree::GetEntry(long long, int) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libTree.so
#12 0x00007f9335473a51 in fitSignalShapeSimul(int*, int, int, int, int, int, double*, double*, double*, double*, double*, double*) () from /afs/cern.ch/user/m/mnadeem/roottut/CMSSW_10_2_5_patch1/src/ZZAnalysis/AnalysisStep/test/CombInputs/fitSignalShapeSimul_C.so
#13 0x00007f933547ba70 in all(int, int, int, int) () from /afs/cern.ch/user/m/mnadeem/roottut/CMSSW_10_2_5_patch1/src/ZZAnalysis/AnalysisStep/test/CombInputs/fitSignalShapeSimul_C.so
#14 0x00007f9334277091 in ?? ()
#15 0x0000000100000000 in ?? ()
#16 0x00007f933547b720 in ?? () from /afs/cern.ch/user/m/mnadeem/roottut/CMSSW_10_2_5_patch1/src/ZZAnalysis/AnalysisStep/test/CombInputs/fitSignalShapeSimul_C.so
#17 0x000000012f52f130 in ?? ()
#18 0x000000000084ad90 in ?? ()
#19 0x00007f9365b486b0 in ?? () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCling.so
#20 0x00007ffe2f52f560 in ?? ()
#21 0x00007f9334277000 in ?? ()
#22 0x00007f9365acc1d2 in cling::Interpreter::RunFunction(clang::FunctionDecl const*, cling::Value*) [clone .part.248] () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCling.so
#23 0x00007f9365ace8b9 in cling::Interpreter::EvaluateInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cling::CompilationOptions, cling::Value*, cling::Transaction**, unsigned long) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCling.so
#24 0x00007f9365acedcb in cling::Interpreter::process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cling::Value*, cling::Transaction**, bool) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCling.so
#25 0x00007f9365b6cfcd in cling::MetaProcessor::process(llvm::StringRef, cling::Interpreter::CompilationResult&, cling::Value*, bool) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCling.so
#26 0x00007f9365a3a54e in HandleInterpreterException(cling::MetaProcessor*, char const*, cling::Interpreter::CompilationResult&, cling::Value*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCling.so
#27 0x00007f9365a47eba in TCling::ProcessLine(char const*, TInterpreter::EErrorCode*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCling.so
#28 0x00007f936a152c54 in TApplication::ProcessLine(char const*, bool, int*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCore.so
#29 0x00007f936a5c4122 in TRint::ProcessLineNr(char const*, char const*, int*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libRint.so
#30 0x00007f936a5c4474 in TRint::HandleTermInput() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libRint.so
#31 0x00007f936a281638 in TUnixSystem::CheckDescriptors() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCore.so
#32 0x00007f936a282d38 in TUnixSystem::DispatchOneEvent(bool) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCore.so
#33 0x00007f936a1b7344 in TSystem::InnerLoop() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCore.so
#34 0x00007f936a1b610f in TSystem::Run() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCore.so
#35 0x00007f936a14f5af in TApplication::Run(bool) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libCore.so
#36 0x00007f936a5c58ef in TRint::Run(bool) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/libRint.so
#37 0x0000000000400c9c in main ()
===========================================================
```

**Comment by linev** [comment]
Please provide more context - platform, compiler, ROOT version and how to reproduce problem

**Comment by AdvaitDhingra** [comment]
This happens when you iterate a loop to much. I'm assuming this is a for-loop, in which case you need to reduce the number of iterations.

**Comment by meena382** [comment]
I was running an old code on CMSSW_10, it gave the above error but then i downgraded to CMSSW_8 and the code ran fine.
