### ISSUE TITLE
Problems with loading dictionaries created with 6.22.06 by 6.22.08

### ISSUE THREAD

**Issue by andriish** [root-project/root#7781]
### Describe the bug
Problems with loading dictionaries created with 6.22.06 by the 6.22.08.
This is quite a minor thing per se but could indicate a larger problem.

### Expected behavior
```
[user@localhost]# root -b -l -q -n -e '{return gSystem->Load("/usr/lib64/root/libHepMC3rootIO.so");}'

[user@localhost]# 
```

Dictionaries are loaded.

### To Reproduce
Install ROOT and HepMC3-rootIO from default Fedora repositories.
```
[user@localhost]# root -b -l -q -n -e '{return gSystem->Load("/usr/lib64/root/libHepMC3rootIO.so");}'

malloc(): invalid size (unsorted)
[user@localhost]# 
```
### Setup
Fedora33 or Rawhide, root 6.22.08 HepMC3-rootIO from the default repositories.

### Additional context
Filled a request to rebuild against newest ROOT
https://bugzilla.redhat.com/show_bug.cgi?id=1945991

**Comment by andriish** [comment]
The bt from gdb when loading this dictionary in other application (ThePEG)
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff73588a4 in __GI_abort () at abort.c:79
#2  0x00007ffff73b2177 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff74c43a7 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff73b9e6c in malloc_printerr (str=str@entry=0x7ffff74c2654 "malloc(): corrupted top size") at malloc.c:5389
#4  0x00007ffff73bd884 in _int_malloc (av=av@entry=0x7ffff74f6a00 <main_arena>, bytes=bytes@entry=48) at malloc.c:4135
#5  0x00007ffff73be8f4 in __GI___libc_malloc (bytes=48) at malloc.c:3078
#6  0x00007ffff7708959 in operator new (sz=sz@entry=48) at ../../../../libstdc++-v3/libsupc++/new_op.cc:50
#7  0x00007ffff368ded2 in TClassTable::FindElementImpl (cname=cname@entry=0x7ffff3e851be "HepMC3::GenParticleData", insert=insert@entry=true) at /usr/src/debug/root-6.22.08-1.fc33.x86_64/core/cont/src/TClassTable.cxx:525
#8  0x00007ffff368e591 in TClassTable::Add (cname=0x7ffff3e851be "HepMC3::GenParticleData", id=<optimized out>, info=..., dict=0x7ffff3e81a40 <ROOT::HepMC3cLcLGenParticleData_Dictionary()>, pragmabits=4)
    at /usr/src/debug/root-6.22.08-1.fc33.x86_64/core/cont/src/TClassTable.cxx:352
#9  0x00007ffff36fd338 in ROOT::TGenericClassInfo::TGenericClassInfo (this=this@entry=0x7ffff3e8c340 <ROOT::GenerateInitInstanceLocal(HepMC3::GenParticleData const*)::instance>, fullClassname=fullClassname@entry=0x7ffff3e851be "HepMC3::GenParticleData", 
    declFileName=declFileName@entry=0x7ffff3e851a0 "HepMC3/Data/GenParticleData.h", declFileLine=declFileLine@entry=24, info=..., action=<optimized out>, dictionary=0x7ffff3e81a40 <ROOT::HepMC3cLcLGenParticleData_Dictionary()>, isa=0xe09a50, pragmabits=4, 
    sizof=56) at /usr/src/debug/root-6.22.08-1.fc33.x86_64/core/meta/src/TGenericClassInfo.cxx:102
#10 0x00007ffff3e819a9 in ROOT::GenerateInitInstanceLocal () at /usr/src/debug/HepMC3-3.2.3-1.fc33.x86_64/x86_64-redhat-linux-gnu/rootIO/G__HepMC3rootIO.cxx:108
#11 0x00007ffff3e79ef9 in _sub_I_65535_0.0 () at /usr/include/c++/10/bits/allocator.h:162
#12 0x00007ffff7fe18de in call_init (l=<optimized out>, argc=argc@entry=7, argv=argv@entry=0x7fffffffe028, env=env@entry=0x7fffffffe068) at dl-init.c:74
#13 0x00007ffff7fe19c8 in call_init (env=0x7fffffffe068, argv=0x7fffffffe028, argc=7, l=<optimized out>) at dl-init.c:37
#14 _dl_init (main_map=0xd236b0, argc=7, argv=0x7fffffffe028, env=0x7fffffffe068) at dl-init.c:121
#15 0x00007ffff746f2e5 in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:182
#16 0x00007ffff7fe5e25 in dl_open_worker (a=a@entry=0x7fffffffc710) at dl-open.c:783
#17 0x00007ffff746f288 in __GI__dl_catch_exception (exception=0x7fffffffc6f0, operate=0x7ffff7fe5a40 <dl_open_worker>, args=0x7fffffffc710) at dl-error-skeleton.c:208
#18 0x00007ffff7fe565e in _dl_open (file=0x7fffffffc6f0 "\220\302", <incomplete sequence \322>, mode=-2147483391, caller_dlopen=0x7ffff7ca991a <ThePEG::DynamicLoader::loadcmd(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)+122>, 
    nsid=-2, argc=7, argv=0x7fffffffe028, env=0x7fffffffe068) at dl-open.c:864
#19 0x00007ffff785839c in dlopen_doit (a=a@entry=0x7fffffffc940) at dlopen.c:66
#20 0x00007ffff746f288 in __GI__dl_catch_exception (exception=exception@entry=0x7fffffffc8e0, operate=0x7ffff7858340 <dlopen_doit>, args=0x7fffffffc940) at dl-error-skeleton.c:208
#21 0x00007ffff746f353 in __GI__dl_catch_error (objname=0x7ffff785c050 <last_result+16>, errstring=0x7ffff785c058 <last_result+24>, mallocedp=0x7ffff785c048 <last_result+8>, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:227
#22 0x00007ffff7858bd9 in _dlerror_run (operate=operate@entry=0x7ffff7858340 <dlopen_doit>, args=args@entry=0x7fffffffc940) at dlerror.c:170
#23 0x00007ffff7858428 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#24 0x00007ffff7ca991a in ThePEG::DynamicLoader::loadcmd (file="/usr/lib64/ThePEG/HepMCAnalysis.so") at /usr/include/c++/10/bits/basic_string.h:229```
```

**Comment by pcanal** [comment]
> Problems with loading dictionaries created with 6.22.06 by the 6.22.08.

Dictionary source files and related files (rootmap, rootpcm and pcm) must be rebuild whenever the ROOT version change.

**Comment by andriish** [comment]
Hi @pcanal ,

My understanding was that the full rebuild is needed only for the version bump, but not for patch level bump. But if so, then the difference between versions and patchlevels is much more blured.


Andrii

P.S. please close this issue if this is the expected behaviour.

**Comment by Axel-Naumann** [comment]
Indeed, we don't guarantee ABI stability for patch releases. Most people cope (it has never been a huge issue) and it gives us the freedom to keep the LHC experiments working at a reasonable cost ;-) Patch level for us simply means "it does not have new features, only bug fixes".
