### ISSUE TITLE
Build option for Address Sanitizer is broken

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#7968]
### Describe the bug
`cmake -Dasan=ON` uses `add_compile_options` to add `-fsanitize=address` for all C++ files. This does not affect externally pulled in dependencies, in particular Clad.

### Expected behavior
The option should result in a build where *all* components are built with Address Sanitizer.

### To Reproduce
Configure with `-Dasan=ON` and notice that ASan reports a `use-after-poison` when only starting `./bin/root.exe`.

**Comment by Axel-Naumann** [comment]
Do you have the asan report available?

**Comment by hahnjo** [comment]
> Do you have the asan report available?

I can re-generate it :smile: 
```
=================================================================
==4081163==ERROR: AddressSanitizer: use-after-poison on address 0x62100013a218 at pc 0x7fa3a1d48622 bp 0x7ffc1d2cc110 sp 0x7ffc1d2cc100
READ of size 8 at 0x62100013a218 thread T0
    #0 0x7fa3a1d48621 in clang::LookupResult::configure() (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0xae72621)
    #1 0x7fa39cedfa0c in clad::plugin::CladPlugin::ShouldProcessDecl(clang::DeclGroupRef) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x6009a0c)

0x62100013a218 is located 1304 bytes inside of 4096-byte region [0x621000139d00,0x62100013ad00)
allocated by thread T0 here:
    #0 0x7fa3b6ba0ba8 in __interceptor_malloc (/lib64/libasan.so.5+0xefba8)
    #1 0x7fa39cfca34e in llvm::safe_malloc(unsigned long) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x60f434e)
    #2 0x7fa39f9c1d4e in llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096ul, 4096ul>::Allocate(unsigned long, unsigned long) [clone .constprop.3114] (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x8aebd4e)
    #3 0x7fa39fbd2245 in clang::ASTReader::ReadAST(llvm::StringRef, clang::serialization::ModuleKind, clang::SourceLocation, unsigned int, llvm::SmallVectorImpl<clang::ASTReader::ImportedSubmodule>*) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x8cfc245)
    #4 0x7fa39e60ef42 in clang::CompilerInstance::loadModule(clang::SourceLocation, llvm::ArrayRef<std::pair<clang::IdentifierInfo*, clang::SourceLocation> >, clang::Module::NameVisibilityKind, bool) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x7738f42)
    #5 0x7fa3acfbd1fb in clang::Preprocessor::HandleHeaderIncludeOrImport(clang::SourceLocation, clang::Token&, clang::Token&, clang::SourceLocation, clang::DirectoryLookup const*, clang::FileEntry const*) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x160e71fb)
    #6 0x7fa3acfc5f6b in clang::Preprocessor::HandleIncludeDirective(clang::SourceLocation, clang::Token&, clang::DirectoryLookup const*, clang::FileEntry const*) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x160eff6b)
    #7 0x7fa3acfd6061 in clang::Preprocessor::HandleDirective(clang::Token&) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x16100061)
    #8 0x7fa3ace765c6 in clang::Lexer::LexTokenInternal(clang::Token&, bool) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x15fa05c6)
    #9 0x7fa3ace7be1a in clang::Lexer::Lex(clang::Token&) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x15fa5e1a)
    #10 0x7fa3ad12b926 in clang::Preprocessor::Lex(clang::Token&) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x16255926)
    #11 0x7fa39ccbc639 in clang::Parser::ConsumeToken() (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x5de6639)
    #12 0x7fa39f915182 in clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x8a3f182)
    #13 0x7fa39c83c0cd in cling::IncrementalParser::ParseInternal(llvm::StringRef) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x59660cd)
    #14 0x7fa39c841bc5 in cling::IncrementalParser::Initialize(llvm::SmallVectorImpl<llvm::PointerIntPair<cling::Transaction*, 2u, cling::IncrementalParser::EParseResult, llvm::PointerLikeTypeTraits<cling::Transaction*>, llvm::PointerIntPairInfo<cling::Transaction*, 2u, llvm::PointerLikeTypeTraits<cling::Transaction*> > > >&, bool) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x596bbc5)
    #15 0x7fa39c7fb2e4 in cling::Interpreter::Interpreter(int, char const* const*, char const*, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&, bool, cling::Interpreter const*) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x59252e4)
    #16 0x7fa39c2ce328 in TCling::TCling(char const*, char const*, char const* const*) (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x53f8328)
    #17 0x7fa39c2d9688 in CreateInterpreter (/home/jhahnfel/ROOT/build-asan/lib/libCling.so+0x5403688)
    #18 0x7fa3b62514ef in TROOT::InitInterpreter() (/home/jhahnfel/ROOT/build-asan/lib/libCore.so+0x3644ef)
    #19 0x7fa3b6252556 in ROOT::Internal::GetROOT2() (/home/jhahnfel/ROOT/build-asan/lib/libCore.so+0x365556)
    #20 0x7fa3b628731c in TApplication::TApplication(char const*, int*, char**, void*, int) (/home/jhahnfel/ROOT/build-asan/lib/libCore.so+0x39a31c)
    #21 0x7fa3b7c33d7b in TRint::TRint(char const*, int*, char**, void*, int, bool) (/home/jhahnfel/ROOT/build-asan/lib/libRint.so+0x29d7b)
    #22 0x20266e in main (/home/jhahnfel/ROOT/build-asan/bin/root.exe+0x20266e)
    #23 0x7fa3b4ffe7b2 in __libc_start_main (/lib64/libc.so.6+0x237b2)
```

**Comment by hageboeck** [comment]
- I tested on mac: No problems.
- The nightly asan build has clad enabled, but doesn't have the same problem:
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Exp./job/root-exp-asan/LABEL=ROOT-ubuntu2004-clang,SPEC=asan,V=master/lastBuild/consoleFull
- Testing on my centos8 now.

Those are all clang builds, though. I suspect that it's a gcc problem. Did you use gcc?

**Comment by hahnjo** [comment]
@hageboeck 

> Those are all clang builds, though. I suspect that it's a gcc problem. Did you use gcc?

Yes, I was using the default GCC 8 from CentOS 8.

**Comment by hageboeck** [comment]
Maybe we should just drop support for gcc, because ROOT needs some custom suppressions that only work with clang ...
