### ISSUE TITLE
Creating `RH1D` with default constructor leads to segfault while filling

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#7971]
### Describe the bug

I get a segfault with the following program
```cpp
#include <ROOT/RHist.hxx>
#include <TRandom.h>

int main(){
    ROOT::Experimental::RH1D myhisto{};

    for (auto i = 0; i < 1000; i++){
        myhisto.Fill(gRandom->Gaus(10,1));
    }
}
```
```
$: g++ -o create_rh1d create_rh1d.cpp `root-config --cflags --glibs`
$: ./create_rh1d 

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fbb37f46c8a in __GI___wait4 (pid=74253, stat_loc=stat_loc
entry=0x7fffe5f04fe8, options=options
entry=0, usage=usage
entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00007fbb37f46c4b in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc
entry=0x7fffe5f04fe8, options=options
entry=0) at waitpid.c:38
#2  0x00007fbb37ec2897 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:172
#3  0x00007fbb39c9ecdc in TUnixSystem::StackTrace() () from /home/vpadulan/Programs/rootproject/rootinstall/v6-24-00/lib/libCore.so
#4  0x00007fbb39c9c2d5 in TUnixSystem::DispatchSignals(ESignals) () from /home/vpadulan/Programs/rootproject/rootinstall/v6-24-00/lib/libCore.so
#5  <signal handler called>
#6  0x0000000000000000 in ?? ()
#7  0x000000000040237c in ROOT::Experimental::RHist<1, double, ROOT::Experimental::RHistStatContent, ROOT::Experimental::RHistStatUncertainty>::Fill(ROOT::Experimental::Hist::RCoordArray<1> const&, double) ()
#8  0x00000000004021e4 in main ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x0000000000000000 in ?? ()
#7  0x000000000040237c in ROOT::Experimental::RHist<1, double, ROOT::Experimental::RHistStatContent, ROOT::Experimental::RHistStatUncertainty>::Fill(ROOT::Experimental::Hist::RCoordArray<1> const&, double) ()
#8  0x00000000004021e4 in main ()
===========================================================
```

### Expected behavior

No segfault, plus either
* Entries are filled correctly
* I get a clear error of what I'm doing wrong
### To Reproduce

Everything is shown above
### Setup

ROOT 6.24.00
Built on Fedora32 with following cmake command `cmake -GNinja -DCMAKE_BUILD_TYPE=Release`

**Comment by dpiparo** [comment]
We are really grateful for this feedback. The initial RHist prototype benefited a lot from it and became an even better base for the work that came after (see, e.g. https://indico.cern.ch/event/1403741/#1-thoughts-on-efficient-parall). I am marking this item as "Won't fix", but it should really be "Thank you!".
