### ISSUE TITLE
Minimizer class bug in ROOT 6.24/00

### ISSUE THREAD

**Issue by matLogh** [root-project/root#8233]
Hi!
I would like to report bug in the ROOT 6.24/00 in the minimizer class. Honestly I don't understand what the problem is, but nor mine, nor the example code _NumericalMinimization.C_ does not run under this version of ROOT. I don't think its necessary, but I'm adding stack trace from run of the _NumericalMinimization()_ function from the example code.

cheers,
matus
```
===========================================================
#5  0x00007fc0f68a084c in NumericalMinimization(char const*, char const*, int) () from /home/mbalogh/runningIntegral/simulations/VW_compare/test_cxx.so
#6  0x00007fc0f689b059 in ?? ()
#7  0x0000000001fdea40 in ?? ()
#8  0x0000000001fdea40 in ?? ()
#9  0x0000000001de3a50 in ?? ()
#10 0x00007fc0f68a07c0 in ?? () from /home/mbalogh/runningIntegral/simulations/VW_compare/test_cxx.so
#11 0x00007ffea57b5a50 in ?? ()
#12 0x00007ffea57b5a50 in ?? ()
#13 0x0000000001e9b430 in ?? ()
#14 0x00007fc0f0915425 in cling::IncrementalExecutor::executeWrapper(llvm::StringRef, cling::Value*) const () from /opt/root_v6.24/build_dir/lib/libCling.so
#15 0x00007fc0f088de85 in cling::Interpreter::RunFunction(clang::FunctionDecl const*, cling::Value*) () from /opt/root_v6.24/build_dir/lib/libCling.so
#16 0x00007fc0f088f66d in cling::Interpreter::EvaluateInternal(std::string const&, cling::CompilationOptions, cling::Value*, cling::Transaction**, unsigned long) () from /opt/root_v6.24/build_dir/lib/libCling.so
#17 0x00007fc0f088f858 in cling::Interpreter::process(std::string const&, cling::Value*, cling::Transaction**, bool) () from /opt/root_v6.24/build_dir/lib/libCling.so
#18 0x00007fc0f0973e08 in cling::MetaProcessor::process(llvm::StringRef, cling::Interpreter::CompilationResult&, cling::Value*, bool) () from /opt/root_v6.24/build_dir/lib/libCling.so
#19 0x00007fc0f079579c in HandleInterpreterException(cling::MetaProcessor*, char const*, cling::Interpreter::CompilationResult&, cling::Value*) () from /opt/root_v6.24/build_dir/lib/libCling.so
===========================================================
```

**Comment by matLogh** [comment]
> 
> 
> Do you have `$ROOTSYS/lib/libMinuit2.so`?

I totally forgot to compile it with Minuit2. After rebuilding it work just fine, sorry for wasting your time.
