### ISSUE TITLE
cling crashes on conditional parameter in template

### ISSUE THREAD

**Issue by linev** [root-project/root#8494]
- [*] Checked for duplicates

Following class declaration crashes cling:
```cpp
template<typename T, typename std::enable_if<std::is_enum<T>::value>::type* = nullptr>
class RAttrEnum : public RAttrValue<T> {
}
```

**Comment by Axel-Naumann** [comment]
Can I have a reproducer and some more info?

- how do I get that code into cling?
- `error: no template named 'RAttrValue'`
- how does it crash? Do you have an error message / backtrace?
- Is the missing semicolon after the class decl intentional?

**Comment by linev** [comment]
Just a code from my PR: https://github.com/root-project/root/pull/8493
Attached is reproducer.

[problem.cxx.gz](https://github.com/root-project/root/files/6687053/problem.cxx.gz)

**Comment by linev** [comment]
Code runs in interactive session, but crashes when doing `root problem.cxx+`

**Comment by Axel-Naumann** [comment]
Could you paste the error output / backtrace, please?

**Comment by linev** [comment]
Backtrace:
```
#5  0x00007f4aa4b5f738 in (anonymous namespace)::shouldIgnore(clang::Decl const*) () from /home/linev/build/webgui/lib/libCling.so
#6  0x00007f4aa6f911e0 in clang::Decl::getASTContext() const () from /home/linev/build/webgui/lib/libCling.so
#7  0x00007f4aa4b5f9e7 in cling::DeclCollector::HandleCXXStaticMemberVarInstantiation(clang::VarDecl*) () from /home/linev/build/webgui/lib/libCling.so
#8  0x00007f4aa5017378 in clang::MultiplexConsumer::HandleCXXStaticMemberVarInstantiation(clang::VarDecl*) () from /home/linev/build/webgui/lib/libCling.so
#9  0x00007f4aa59c3c08 in clang::Sema::InstantiateVariableDefinition(clang::SourceLocation, clang::VarDecl*, bool, bool, bool) () from /home/linev/build/webgui/lib/libCling.so
#10 0x00007f4aa5666c03 in DoMarkVarDeclReferenced(clang::Sema&, clang::SourceLocation, clang::VarDecl*, clang::Expr*) () from /home/linev/build/webgui/lib/libCling.so
#11 0x00007f4aa566e525 in clang::Sema::BuildDeclRefExpr(clang::ValueDecl*, clang::QualType, clang::ExprValueKind, clang::DeclarationNameInfo const&, clang::NestedNameSpecifierLoc, clang::NamedDecl*, clang::SourceLocation, clang::TemplateArgumentListInfo const*) () from /home/linev/build/webgui/lib/libCling.so
#12 0x00007f4aa568b13c in clang::Sema::BuildDeclarationNameExpr(clang::CXXScopeSpec const&, clang::DeclarationNameInfo const&, clang::NamedDecl*, clang::NamedDecl*, clang::TemplateArgumentListInfo const*, bool) () from /home/linev/build/webgui/lib/libCling.so
#13 0x00007f4aa568b7ce in clang::Sema::BuildDeclarationNameExpr(clang::CXXScopeSpec const&, clang::LookupResult&, bool, bool) () from /home/linev/build/webgui/lib/libCling.so
#14 0x00007f4aa568c378 in clang::Sema::BuildQualifiedDeclarationNameExpr(clang::CXXScopeSpec&, clang::DeclarationNameInfo const&, bool, clang::Scope const*, clang::TypeSourceInfo**) () from /home/linev/build/webgui/lib/libCling.so
#15 0x00007f4aa59a162a in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDependentScopeDeclRefExpr(clang::DependentScopeDeclRefExpr*, bool, clang::TypeSourceInfo**) () from /home/linev/build/webgui/lib/libCling.so
#16 0x00007f4aa59948bc in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateArgument(clang::TemplateArgumentLoc const&, clang::TemplateArgumentLoc&, bool) () from /home/linev/build/webgui/lib/libCling.so
#17 0x00007f4aa5996dc2 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateSpecializationType(clang::TypeLocBuilder&, clang::TemplateSpecializationTypeLoc, clang::TemplateName) () from /home/linev/build/webgui/lib/libCling.so
#18 0x00007f4aa5993be9 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTSIInObjectScope(clang::TypeLoc, clang::QualType, clang::NamedDecl*, clang::CXXScopeSpec&) [clone .isra.0] () from /home/linev/build/webgui/lib/libCling.so
#19 0x00007f4aa5994499 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformNestedNameSpecifierLoc(clang::NestedNameSpecifierLoc, clang::QualType, clang::NamedDecl*) () from /home/linev/build/webgui/lib/libCling.so
#20 0x00007f4aa5998edf in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDependentNameType(clang::TypeLocBuilder&, clang::DependentNameTypeLoc, bool) () from /home/linev/build/webgui/lib/libCling.so
#21 0x00007f4aa598ea8c in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeLocBuilder&, clang::TypeLoc) () from /home/linev/build/webgui/lib/libCling.so
#22 0x00007f4aa5990757 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformPointerType(clang::TypeLocBuilder&, clang::PointerTypeLoc) () from /home/linev/build/webgui/lib/libCling.so
#23 0x00007f4aa598ee52 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeLocBuilder&, clang::TypeLoc) () from /home/linev/build/webgui/lib/libCling.so
#24 0x00007f4aa5991a8e in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeSourceInfo*) () from /home/linev/build/webgui/lib/libCling.so
#25 0x00007f4aa5992c97 in clang::Sema::SubstType(clang::QualType, clang::MultiLevelTemplateArgumentList const&, clang::SourceLocation, clang::DeclarationName) () from /home/linev/build/webgui/lib/libCling.so
#26 0x00007f4aa58d85f5 in clang::Sema::CheckTemplateArgument(clang::NamedDecl*, clang::TemplateArgumentLoc&, clang::NamedDecl*, clang::SourceLocation, clang::SourceLocation, unsigned int, llvm::SmallVectorImpl<clang::TemplateArgument>&, clang::Sema::CheckTemplateArgumentKind) () from /home/linev/build/webgui/lib/libCling.so
#27 0x00007f4aa58d8c7e in clang::Sema::CheckTemplateArgumentList(clang::TemplateDecl*, clang::SourceLocation, clang::TemplateArgumentListInfo&, bool, llvm::SmallVectorImpl<clang::TemplateArgument>&, bool) () from /home/linev/build/webgui/lib/libCling.so
#28 0x00007f4aa58da8da in clang::Sema::CheckTemplateIdType(clang::TemplateName, clang::SourceLocation, clang::TemplateArgumentListInfo&) () from /home/linev/build/webgui/lib/libCling.so
#29 0x00007f4aa58ddc37 in clang::Sema::ActOnTemplateIdType(clang::Scope*, clang::CXXScopeSpec&, clang::SourceLocation, clang::OpaquePtr<clang::TemplateName>, clang::IdentifierInfo*, clang::SourceLocation, clang::SourceLocation, llvm::MutableArrayRef<clang::ParsedTemplateArgument>, clang::SourceLocation, bool, bool) () from /home/linev/build/webgui/lib/libCling.so
#30 0x00007f4aa5241260 in clang::Parser::AnnotateTemplateIdTokenAsType(bool) () from /home/linev/build/webgui/lib/libCling.so
#31 0x00007f4aa51b987a in clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) () from /home/linev/build/webgui/lib/libCling.so
#32 0x00007f4aa51bb711 in clang::Parser::ParseSpecifierQualifierList(clang::DeclSpec&, clang::AccessSpecifier, clang::Parser::DeclSpecContext) () from /home/linev/build/webgui/lib/libCling.so
#33 0x00007f4aa51bbd87 in clang::Parser::ParseTypeName(clang::SourceRange*, clang::DeclaratorContext, clang::AccessSpecifier, clang::Decl**, clang::ParsedAttributes*) () from /home/linev/build/webgui/lib/libCling.so
#34 0x00007f4aa4ac84b8 in clang::FunctionDecl const* cling::execFindFunction<cling::ParseProto, clang::FunctionDecl const*>(clang::Parser&, cling::Interpreter*, cling::LookupHelper&, clang::Decl const*, llvm::StringRef, cling::ParseProto::ArgsInput const&, bool, clang::FunctionDecl const* (*)(clang::DeclContext*, bool, llvm::SmallVectorImpl<clang::Expr*> const&, clang::LookupResult&, clang::DeclarationNameInfo&, clang::TemplateArgumentListInfo const*, clang::ASTContext&, clang::Parser&, clang::Sema&, cling::LookupHelper::DiagSetting), cling::LookupHelper::DiagSetting) () from /home/linev/build/webgui/lib/libCling.so
#35 0x00007f4aa4ac3dc7 in cling::LookupHelper::findFunctionProto(clang::Decl const*, llvm::StringRef, llvm::StringRef, cling::LookupHelper::DiagSetting, bool) const () from /home/linev/build/webgui/lib/libCling.so
#36 0x00007f4aa493a51f in ROOT::TMetaUtils::GetFuncWithProto(clang::Decl const*, char const*, char const*, cling::Interpreter const&, bool) () from /home/linev/build/webgui/lib/libCling.so
#37 0x00007f4aa495193d in ROOT::TMetaUtils::WriteClassInit(std::ostream&, ROOT::TMetaUtils::AnnotatedRecordDecl const&, clang::CXXRecordDecl const*, cling::Interpreter const&, ROOT::TMetaUtils::TNormalizedCtxt const&, std::__cxx11::list<ROOT::TMetaUtils::RConstructorType, std::allocator<ROOT::TMetaUtils::RConstructorType> > const&, bool&) () from /home/linev/build/webgui/lib/libCling.so
#38 0x00007f4aa499df7b in GenerateFullDict(std::ostream&, cling::Interpreter&, RScanner&, std::__cxx11::list<ROOT::TMetaUtils::RConstructorType, std::allocator<ROOT::TMetaUtils::RConstructorType> > const&, bool, bool, bool) () from /home/linev/build/webgui/lib/libCling.so
#39 0x00007f4aa49aa7a3 in RootClingMain(int, char**, bool) () from /home/linev/build/webgui/lib/libCling.so
#40 0x00007f4aa49ae06c in ROOT_rootcling_Driver () from /home/linev/build/webgui/lib/libCling.so
#41 0x000000000040115e in main ()
```

**Comment by dpiparo** [comment]
Hi @linev , for me the test works. Please do not hesitate to re-open if still broken for you.
