### ISSUE TITLE
ROOT Assertion During Dictionary Loading (2021.06.30.)

### ISSUE THREAD

**Issue by krasznaa** [root-project/root#8578]
- [x] Checked for duplicates

### Describe the bug

Another incarnation of the ATLAS xAOD EDM overwhelming ROOT is at foot. :frowning: I was trying to understand the issue better before turning to you guys, but I feel that I would need to learn much more about LLVM/Cling to get further than what I'm willing to do...

So... in a particular PyROOT test I encounter the following assertion in a debug build:

```
(gdb) bt
#0  0x00007faf4a49d3d7 in raise () from /lib64/libc.so.6
#1  0x00007faf4a49eac8 in abort () from /lib64/libc.so.6
#2  0x00007faf4a4961a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007faf4a496252 in __assert_fail () from /lib64/libc.so.6
#4  0x00007faf409453d0 in clang::Sema::LookupQualifiedName (this=0x14ab0b0, R=..., LookupCtx=0x3035ca0, InUnqualifiedLookup=false)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Sema/SemaLookup.cpp:2128
#5  0x00007faf40945d1b in clang::Sema::LookupQualifiedName (this=0x14ab0b0, R=..., LookupCtx=0x3035ca0, SS=...)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Sema/SemaLookup.cpp:2364
#6  0x00007faf40b30acf in clang::Sema::CheckTypenameType (this=0x14ab0b0, Keyword=clang::ETK_Typename, KeywordLoc=..., QualifierLoc=..., II=..., IILoc=...)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplate.cpp:10051
#7  0x00007faf40c7d53d in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::RebuildDependentNameType (this=0x7ffdb628d120, Keyword=clang::ETK_Typename, 
    KeywordLoc=..., QualifierLoc=..., Id=0x7dcc138, IdLoc=..., DeducedTSTContext=false)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Sema/TreeTransform.h:1057
#8  0x00007faf40c69016 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDependentNameType (this=0x7ffdb628d120, TLB=..., TL=..., 
    DeducedTSTContext=false) at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Sema/TreeTransform.h:6295
#9  0x00007faf40c6db87 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDependentNameType (this=0x7ffdb628d120, TLB=..., TL=...)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Sema/TreeTransform.h:6282
#10 0x00007faf40c56ad3 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType (this=0x7ffdb628d120, TLB=..., T=...)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/include/clang/AST/TypeNodes.def:105
#11 0x00007faf40c56212 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType (this=0x7ffdb628d120, DI=0xa0f3090)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Sema/TreeTransform.h:4252
#12 0x00007faf40c4d485 in clang::Sema::SubstType (this=0x14ab0b0, T=0xa0f3090, Args=..., Loc=..., Entity=..., AllowDeducedTST=false)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplateInstantiate.cpp:1605
#13 0x00007faf40b1c1f7 in SubstDefaultTemplateArgument (SemaRef=..., Template=0xcd78f48, TemplateLoc=..., RAngleLoc=..., Param=0xcd78e10, Converted=...)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplate.cpp:4710
#14 0x00007faf40b1e5d1 in clang::Sema::CheckTemplateArgumentList (this=0x14ab0b0, Template=0xcd78f48, TemplateLoc=..., TemplateArgs=..., PartialTemplateArgs=false, Converted=..., 
    UpdateArgsWithConversions=true)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplate.cpp:5427
#15 0x00007faf40b16979 in clang::Sema::CheckTemplateIdType (this=0x14ab0b0, Name=..., TemplateLoc=..., TemplateArgs=...)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Sema/SemaTemplate.cpp:3323
#16 0x00007faf4035f07a in clang::Sema::ActOnCXXNestedNameSpecifier (this=0x14ab0b0, S=0x17d2a80, SS=..., TemplateKWLoc=..., OpaqueTemplate=..., TemplateNameLoc=..., 
    LAngleLoc=..., TemplateArgsIn=..., RAngleLoc=..., CCLoc=..., EnteringContext=false)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Sema/SemaCXXScopeSpec.cpp:980
#17 0x00007faf4007023d in clang::Parser::ParseOptionalCXXScopeSpecifier (this=0x1575b10, SS=..., ObjectType=..., EnteringContext=false, MayBePseudoDestructor=0x0, 
    IsTypename=false, LastII=0x0, OnlyNamespace=false)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Parse/ParseExprCXX.cpp:362
#18 0x00007faf400e004c in clang::Parser::TryAnnotateCXXScopeToken (this=0x1575b10, EnteringContext=false)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/llvm/src/tools/clang/lib/Parse/Parser.cpp:1994
#19 0x00007faf3f4ea7ca in cling::LookupHelper::findScope (this=0x142a600, className=..., diagOnOff=cling::LookupHelper::NoDiagnostics, resultType=0x7ffdb628eb00, 
    instantiateTemplate=true) at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/interpreter/cling/lib/Interpreter/LookupHelper.cpp:631
#20 0x00007faf3f41d1f3 in TClingClassInfo::TClingClassInfo (this=0x7ffdb628eb80, interp=0x131d620, name=0x209836f0 "DataVector<xAOD::TauJet_v3>", intantiateTemplate=true)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/core/metacling/src/TClingClassInfo.cxx:88
#21 0x00007faf3f4207f6 in TClingClassInfo::IsEnum (interp=0x131d620, name=0x209836f0 "DataVector<xAOD::TauJet_v3>")
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/core/metacling/src/TClingClassInfo.cxx:817
#22 0x00007faf3f2d407c in TCling::ClassInfo_IsEnum (this=0x13e4e80, name=0x209836f0 "DataVector<xAOD::TauJet_v3>")
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/core/metacling/src/TCling.cxx:8239
#23 0x00007faf49954765 in Cppyy::IsEnum (type_name=...)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx:948
#24 0x00007faf49952302 in Cppyy::ResolveName (cppitem_name=...)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx:410
#25 0x00007faf49952db6 in Cppyy::GetScope (sname=...)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx:510
#26 0x00007faf49cac9bc in CPyCppyy::CreateScopeProxy (name=..., parent=0x31c9c90)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/bindings/pyroot/cppyy/CPyCppyy/src/ProxyWrappers.cxx:541
#27 0x00007faf49c84ccf in CPyCppyy::meta_getattro (pyclass=0x31c9c90, pyname=0x7faf03154b20)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/ROOT/bindings/pyroot/cppyy/CPyCppyy/src/CPPScope.cxx:324
#28 0x00007faf4b479097 in _PyObject_LookupAttr (v=0x31c9c90, name=<optimized out>, result=result@entry=0x7ffdb628f638)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/Python/Objects/object.c:978
#29 0x00007faf4b510d49 in builtin_hasattr_impl (module=<optimized out>, name=<optimized out>, obj=<optimized out>)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/Python/Python/bltinmodule.c:1140
#30 builtin_hasattr (module=<optimized out>, args=0x7faf298e3388, nargs=<optimized out>)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/Python/Python/clinic/bltinmodule.c.h:449
#31 0x00007faf4b473fe4 in cfunction_vectorcall_FASTCALL (func=0x7faf4baac6d0, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/Python/Objects/methodobject.c:422
#32 0x00007faf4b40432d in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/Python/Include/cpython/abstract.h:127
#33 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x125f820)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/Python/Python/ceval.c:4963
#34 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/Python/Python/ceval.c:3500
#35 0x00007faf4b3ff88b in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=2, globals=<optimized out>)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/Python/Objects/call.c:283
#36 0x00007faf4b430ef7 in _PyObject_Vectorcall (kwnames=0x0, nargsf=2, args=0x7ffdb628f800, callable=0x7faf298dbaf0)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/Python/Include/cpython/abstract.h:127
#37 method_vectorcall (method=<optimized out>, args=<optimized out>, nargsf=<optimized out>, kwnames=0x0)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/Python/Objects/classobject.c:89
#38 0x00007faf4b42df36 in _PyObject_Vectorcall (kwnames=0x0, nargsf=1, args=0x7ffdb628f890, callable=0x7faf4b960e80)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/Python/Include/cpython/abstract.h:127
#39 _PyObject_FastCall (nargs=1, args=0x7ffdb628f890, func=0x7faf4b960e80)
    at /data/hdd-4tb/projects/ATLASG-1602/externals/build/AnalysisBaseExternals/src/Python/Include/cpython/abstract.h:147
...
```

Unfortunately all I could decipher from this is that things go south while accessing the `DataVector<xAOD::TauJet_v3>` type in Python. That access itself happens in a fairly complicated way itself, in this helper code:

https://gitlab.cern.ch/atlas/athena/-/blob/master/Control/xAODRootAccess/python/GenerateDVIterators.py

As before, I found that by explicitly accessing types "in the right order", I can work around the issue. (See: https://gitlab.cern.ch/atlas/athena/-/merge_requests/44843) But I'd really like to understand what the underlying issue actually is.

Note that this problem only shows up in a debug build. In an optimised build the test in question runs just fine.

### Expected behavior

The code should not encounter an assertion inside LLVM/Cling.

### To Reproduce

Unfortunately this would be pretty involved to describe. :frowning: Especially the setup that I used with Cling compiled in Debug mode. So I'm rather just hoping for input on how I myself could debug this further.

### Setup

  - ROOT 6.24/00
  - `x86_64-centos7-gcc8-dbg`
  - ROOT built using: https://gitlab.cern.ch/atlas/atlasexternals/-/tree/master/External/ROOT

### Additional context

I guess my question is how I could get enough information out of of the `clang::DeclContext` object that the assertion fails on, to understand why the code ended up where it did...

**Comment by dpiparo** [comment]
Hi @krasznaa . I apologise for following up this item only now. I was wondering if I could check with some reproducer whether this is still an issue...

**Comment by dpiparo** [comment]
@krasznaa in absence of a reproducer, I assume ATLAS is now OK. Of course, as usual, I encourage you and the ATLAS team to reopen this issue or to open a new, related one as well as to reach out to me or the ROOT team in the way you see most fit.

**Comment by krasznaa** [comment]
I believe @scott-snyder is following up about our currently active issues. :thinking: Since this has been dormant for so long, let's indeed close it. I don't even remember the circumstances of this ticket anymore... :frowning:
