### ISSUE TITLE
CMAKE_INSTALL_PYTHONDIR on macOS creates broken symlinks

### ISSUE THREAD

**Issue by chrisburr** [root-project/root#8933]
- [x] Checked for duplicates

### Describe the bug

As of 6.24.04, building with `CMAKE_INSTALL_PYTHONDIR` on macOS causes pyroot to not be functional as the installed symlink is:

```
lib/python3.9/site-packages/libcppyy_backend3_9.dylib@ -> ../..//libcppyy_backend3_9.dylib
```
whereas the actually Python module is in:
```
lib/libcppyy3_9.6.24.04.so
```

which causes `import ROOT` to fail: 

```python
Traceback (most recent call last):
  File "/Users/christopherburr/miniconda3/conda-bld/root_base_1630311151559/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/cppyy/__init__.py", line 60, in <module>
    importlib.import_module(libcppyy_mod_name)
  File "/Users/christopherburr/miniconda3/conda-bld/root_base_1630311151559/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'libcppyy3_9'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/christopherburr/miniconda3/conda-bld/root_base_1630311151559/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/ROOT/__init__.py", line 22, in <module>
    import cppyy
  File "/Users/christopherburr/miniconda3/conda-bld/root_base_1630311151559/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/cppyy/__init__.py", line 62, in <module>
    raise ImportError(
ImportError: Failed to import libcppyy3_9. Please check that ROOT has been built for Python 3.9
Tests failed for root_base-6.24.4-py39h04197d9_0.tar.bz2 - moving package to /Users/christopherburr/miniconda3/conda-bld/broken
```

This issue was introduced in https://github.com/root-project/root/commit/aefe374411d9bfecaa4a9eb764aee05f7b76a8e6 as the patch uses `CMAKE_SHARED_LIBRARY_SUFFIX` despite the fact that the suffix is overridden by:

https://github.com/root-project/root/blob/c06ad10a69b6b173fd21692f38394700b635abb0/bindings/pyroot/cppyy/cppyy-backend/CMakeLists.txt#L36-L37

https://github.com/root-project/root/blob/4eab5042f748d08f62f224d44a4ac9c82b9a3a13/cmake/modules/RootMacros.cmake#L37-L48

https://github.com/root-project/root/blob/4eab5042f748d08f62f224d44a4ac9c82b9a3a13/cmake/modules/RootMacros.cmake#L21-L25

### Expected behavior

`CMAKE_INSTALL_PYTHONDIR` creates the correctly named symlinks for the binaries it installed.

**Comment by amadio** [comment]
Yes, I agree that the commit you pointed out is the problem. We need to decide if we fix that to always use .so (not sure what happens to Windows then), or if we let ROOT use .dylib on Mac instead of .so. @Axel-Naumann, please let me know what should be the preferred fix, and I will make a pull request with it.

**Comment by etejedor** [comment]
Discussed with @amadio , probably the least disruptive way to solve this would be to use `.so` again instead of `${CMAKE_SHARED_LIBRARY_SUFFIX}` in cppyy's `CMakeList.txt`s. To be confirmed by @Axel-Naumann .
