### ISSUE TITLE
Code unloading fails assert: "Can not revert previous transactions"

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#9187]
From https://root-forum.cern.ch/t/segmentation-violation-when-re-compiling-cpp-file-after-running/47373

```c++
// minimal.cpp
# include <TRandom3.h>
# include <TH1D.h>
# include <TFile.h>
# include <TCanvas.h>
# include <TStyle.h>

# include <Riostream.h>
# include <iostream>

void particles_decay(int N0, double delta_t, double alpha, int seed = 1) {
    double t=0.;
    double T = 300.;

    int N_survived = N0;
    int N_decayed;

    int N_steps = (int)(T/delta_t);
    int step = 0;

    double r;

    TRandom3 *gRandom = new TRandom3();
    gRandom -> SetSeed(seed);


    TFile file("particles_decay.root", "recreate");

    TCanvas* f = new TCanvas("f");

    //creo oggetto TH1D per disegnare la funzione di decadimento
    TH1D* N_vs_t = new TH1D("N_vs_t", "Number of particles in time", N_steps, 0, T);

    while((t < T) && (N_survived > 0)) {

        N_vs_t -> SetBinContent(step, N_survived);

        //simulo decadimento radioattivo sulle particelle sopravvisute
        N_decayed = 0;
        for(int j=0; j<N_survived; j++){
            r = gRandom -> Rndm();
            if (r < alpha*delta_t) N_decayed++;
        }

        if (N_survived <= N_decayed) break;
        N_survived -= N_decayed;

        t += delta_t;
        step++;
    }

    gStyle -> SetOptFit();
    N_vs_t -> Fit("expo");

    N_vs_t -> DrawCopy();

    //Metto sul file root tutte le robe sovrapposte, nota che f punta al TCanvas aperto sopra, 
    //mentre il file .root con quel nome era stato anche lui creato sopra.
    f -> Print("particles_decay.root");

    file.Close();
}
```
This gives

```
root [0] .L minimal.C
root [1] particles_decay(500, 1., 0.01)
 FCN=51.0153 FROM MIGRAD    STATUS=CONVERGED      40 CALLS          41 TOTAL
                     EDM=4.6871e-07    STRATEGY= 1      ERROR MATRIX ACCURATE 
  EXT PARAMETER                                   STEP         FIRST   
  NO.   NAME      VALUE            ERROR          SIZE      DERIVATIVE 
   1  Constant     6.20101e+00   7.29140e-03   1.63914e-05  -1.00223e-01
   2  Slope       -1.01929e-02   6.74151e-05   1.51443e-07   4.24243e+00
Info in <TCanvas::SaveAs>: ROOT file particles_decay.root has been created
root [2] .L minimal.C
root.exe: /home/axel/build/root/master/src/interpreter/cling/lib/Interpreter/Interpreter.cpp:1513: void cling::Interpreter::unload(cling::Transaction&): Assertion `!T.getTopmostParent()->getNext() && "Can not revert previous transactions"' failed.
```

**Comment by ferdymercury** [comment]
Full stack trace with current master:

```
===========================================================
#11 0x00007f5325a922c7 in cling::DeclUnloader::VisitDecl(clang::Decl*) () from /home/user/build/build-root-Desktop-Debug/lib/libCling.so
#12 0x00007f5325a60355 in cling::TransactionUnloader::unloadDeserializedDeclarations(cling::Transaction*, cling::DeclUnloader&) () from /home/user/build/build-root-Desktop-Debug/lib/libCling.so
#13 0x00007f5325a607e6 in cling::TransactionUnloader::RevertTransaction(cling::Transaction*) () from /home/user/build/build-root-Desktop-Debug/lib/libCling.so
#14 0x00007f5325a42b06 in cling::Interpreter::unload(cling::Transaction&) () from /home/user/build/build-root-Desktop-Debug/lib/libCling.so
#15 0x00007f5325a42c14 in cling::Interpreter::unload(unsigned int) () from /home/user/build/build-root-Desktop-Debug/lib/libCling.so
#16 0x00007f5325b2a616 in cling::MetaSema::actOnUCommand(llvm::StringRef) () from /home/user/build/build-root-Desktop-Debug/lib/libCling.so
#17 0x00007f5325b2e6e2 in cling::MetaSema::actOnLCommand(llvm::StringRef, cling::Transaction**) () from /home/user/build/build-root-Desktop-Debug/lib/libCling.so
#18 0x00007f5325b3e100 in cling::MetaParser::isCommand(cling::MetaSema::ActionResult&, cling::Value*) () from /home/user/build/build-root-Desktop-Debug/lib/libCling.so
#19 0x00007f5325b27630 in cling::MetaProcessor::process(llvm::StringRef, cling::Interpreter::CompilationResult&, cling::Value*, bool) () from /home/user/build/build-root-Desktop-Debug/lib/libCling.so
#20 0x00007f53257e91de in HandleInterpreterException (metaProcessor=0x55845f447920, input_line=0x55846273f280 ".L /tmp/./minimal.cpp", compRes=
0x7ffd87315e20: cling::Interpreter::kSuccess, result=0x7ffd87315e70) at /opt/root_src/core/metacling/src/TCling.cxx:2438
===========================================================
```

Still there with LLVM/Clang 20

**Comment by ferdymercury** [comment]
Slightly related:

https://github.com/root-project/cling/issues/561
https://github.com/root-project/cling/issues/522
https://github.com/root-project/root/issues/18624


eDIT: Still the case with LLVM22 current master
