### ISSUE TITLE
problem fitting 2d function with pyroot

### ISSUE THREAD

**Issue by stroili** [root-project/root#9745]
I'm trying to fit a 2d histogram with a 2d gaussian using pyroot, but I get an error telling me that instead of a 2d function the fit is trying to use a 1d function.
This is the function I have:

```
class gauss2d_function:
  def __init__(self):
    self.n1 = 1.0   # normalization 1
    self.m1 = 60.   # mean 1
    self.s1 = 1.0   # sigma 1
    self.m2 = 60.0  # mean 2
    self.s2 = 1.0   # sigma 2

  def __call__(self, x, parameters):
    import math
    n1 = parameters[0] # normalization 1
    m1 = parameters[1] # mean 1
    s1 = parameters[2] # sigma 1
    m2 = parameters[3] # mean 2
    s2 = parameters[4] # sigma 2

    x1 = x[0]
    y1 = math.exp(-(x1-m1)*(x-m1)/(s1*s1)/2.)
    x2 = x[1]
    y2 = math.exp(-(x2-m2)*(x-m2)/(s2*s2)/2.)

    retval = n1*math.exp(-0.5*(y1*y1+y2*y2))
    
    return retval

```

and here it is the code:

```
  hscat = ROOT.TH2F('scat', 'scatter plot', 3000, xmin, xmax, 200, \
                    tmin, tmax)
.
.
.
.

  func2d = gauss2d_function()
  gaus2d = ROOT.TF2('gauss2d', func2d, xmin, xmax, tmin, tmax, 5)
  hscat.Fit('gauss2d', '+', 'same', lowerlimit, upperlimit)

```
the error is the following:

```
Traceback (most recent call last):
  File "python/crosstalk.py", line 447, in <module>
    main()
  File "python/crosstalk.py", line 436, in main
    doAnalysis(dbcon, path, filename, channel, photon)
  File "python/crosstalk.py", line 216, in doAnalysis
    hscat.Fit('gauss2d', '+', 'same', lowerlimit, upperlimit)
TypeError: none of the 2 overloaded methods succeeded. Full details:
  TFitResultPtr TH1::Fit(TF1* f1, const char* option = "", const char* goption = "", double xmin = 0, double xmax = 0) =>
    TypeError: could not convert argument 1
  TFitResultPtr TH1::Fit(const char* formula, const char* option = "", const char* goption = "", double xmin = 0, double xmax = 0) =>
    TypeError: unsupported operand type(s) for -: 'cppyy.LowLevelView' and 'float'

```
I'm using ROOT 6.24.06 on CentOS 8.

Thank you very much
   Roberto

**Comment by stroili** [comment]
Solved, it was a typo in my code
```
    x1 = x[0]
    y1 = math.exp(-(x1-m1)*(x-m1)/(s1*s1)/2.)
    x2 = x[1]
    y2 = math.exp(-(x2-m2)*(x-m2)/(s2*s2)/2.)
```

```
    x1 = x[0]
    y1 = math.exp(-(x1-m1)*(x1-m1)/(s1*s1)/2.)
    x2 = x[1]
    y2 = math.exp(-(x2-m2)*(x2-m2)/(s2*s2)/2.)
```
